//! Is this image a crease pattern?
//!
//! The gate behind the "Looks like a crease pattern — Detect creases?" offer
//! on a reference image added to the Edit canvas. It has to answer for every
//! image a user drops there, so it runs in a few tens of milliseconds, needs no
//! model download and no ONNX Runtime, and is tuned to stay quiet on what
//! people actually put on that canvas: photographs of folded models, diagram
//! pages, text.
//!
//! The answer comes from about twenty hand features computed on a ≤512 px
//! copy, combined by a small table of shallow decision trees
//! (`likelihood_model.rs`, generated by
//! `scripts/cp-detect/cp-likelihood/fit-model.py` from features this very
//! module produced — there is deliberately no second implementation of the
//! features to drift from). The features that carry the weight are the ones a
//! crease pattern cannot fake:
//!
//! - **Straight-line length** — a probabilistic Hough pass (the crate's
//!   OpenCV port) over Canny edges, and the share of edge pixels those
//!   segments explain.
//! - **Dangling ends** — on a Zhang–Suen skeleton of the ink, the share of
//!   pixels that are endpoints. Creases end at other creases, so a crease
//!   pattern reads ~0; text, diagrams and photographs read 5–20%.
//! - **Orientation lattice** — gradient orientations at edge pixels
//!   concentrate on a 22.5° lattice, with mass on the diagonals; a photograph
//!   is diffuse, a table or floor plan has axes only.
//! - **Full-span segments** — the share of Hough length in segments crossing
//!   most of the image, which is what separates graph paper, blinds and
//!   random full-width lines from a pattern whose creases stop at each other.
//! - Background fraction, coverage uniformity, ink saturation and a
//!   periodicity of the ink projection round it out.
//!
//! Measured on the labelled corpus (see the plan
//! `implementation-plans/cp-detect-canvas-image-entry.md` for the numbers):
//! AUC ≈ 0.98, ~92% recall at ~2% false positives on folded-model photos,
//! ~0% on photographs, text, tables, plans and charts. Evenly spaced grids
//! are the accepted residual — a grid *is* a precrease pattern.

use serde::{Deserialize, Serialize};

use crate::likelihood_model;
use crate::opencv_hough_lines_p::{HoughLinesPConfig, hough_lines_p_opencv_cpu};

/// Longest side the features are computed at. Larger inputs are area-averaged
/// down first; a caller that already has a copy no larger than this saves the
/// resample (and the transfer, on the worker).
pub const LIKELIHOOD_MAX_SIDE: u32 = 512;

/// Number of features the model reads, in [`MODEL_FEATURES`] order.
pub const MODEL_FEATURE_COUNT: usize = 20;

/// The model's input vector, by name and in order. `likelihood_model.rs` must
/// carry the same list — a test checks — so a refit that reorders features
/// cannot silently read the wrong column.
pub const MODEL_FEATURES: [&str; MODEL_FEATURE_COUNT] = [
    "bg_frac",
    "gray_std",
    "lattice22",
    "top4_mass",
    "orient_entropy",
    "line_len_norm",
    "long_line_ratio",
    "endpoint_rate",
    "junction_rate",
    "ends_per_junction",
    "cells_cv",
    "cells_covered",
    "ink_frac",
    "img_sat_mean",
    "diag_mass",
    "ink_to_skel",
    "full_span_frac",
    "mean_seg_len_norm",
    "periodicity",
    "n_peaks",
];

#[derive(Debug, thiserror::Error)]
pub enum LikelihoodError {
    #[error("invalid image dimensions: {width}x{height}")]
    InvalidDimensions { width: u32, height: u32 },
    #[error("rgba length mismatch: expected {expected}, got {actual}")]
    RgbaLengthMismatch { expected: usize, actual: usize },
}

/// Everything the extractor measures. The model reads the [`MODEL_FEATURES`]
/// subset; the rest is kept for the harness and for diagnosing a verdict in
/// the field (`cp_likelihood_score` prints all of it).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CpLikelihoodFeatures {
    /// Size the features were computed at.
    pub width: u32,
    pub height: u32,
    pub aspect: f32,
    /// Share of pixels within ±12 of the luma histogram's mode.
    pub bg_frac: f32,
    pub gray_std: f32,
    /// Share of pixels that differ from a 21 px median by more than 24.
    pub ink_frac: f32,
    /// Share of pixels Canny marks as edges.
    pub edge_frac: f32,
    /// Orientation histogram: mass under the four strongest peaks (±3°).
    pub top4_mass: f32,
    /// Peaks holding at least 4% of the orientation mass each.
    pub n_peaks: u32,
    /// Best mass within ±2.5° of a 22.5° lattice, over all lattice offsets.
    pub lattice22: f32,
    pub lattice45: f32,
    pub lattice90: f32,
    /// In the best 22.5° frame: mass on the two axes 45° from the strongest pair.
    pub diag_mass: f32,
    /// Mass on the strongest axis pair itself.
    pub axis_mass: f32,
    /// Normalised entropy of the orientation histogram (1 = uniform).
    pub orient_entropy: f32,
    /// Probabilistic Hough segments found.
    pub n_lines: u32,
    /// Total segment length over the image's shorter side.
    pub line_len_norm: f32,
    /// Share of edge pixels lying on a segment (drawn 3 px wide).
    pub long_line_ratio: f32,
    /// Share of segment length in segments at least 75% of the shorter side.
    pub full_span_frac: f32,
    pub mean_seg_len_norm: f32,
    /// Peak normalised autocorrelation of the ink's row and column sums.
    pub periodicity: f32,
    /// Skeleton pixels over image pixels.
    pub skel_px_frac: f32,
    /// Skeleton endpoints over skeleton pixels.
    pub endpoint_rate: f32,
    /// Skeleton junction clusters over skeleton pixels.
    pub junction_rate: f32,
    pub ends_per_junction: f32,
    pub n_endpoints: u32,
    pub n_junctions: u32,
    /// Ink pixels per skeleton pixel: a mean stroke width.
    pub ink_to_skel: f32,
    /// The ink's 1st–99th percentile box as a share of the image.
    pub ink_bbox_fill: f32,
    pub ink_bbox_aspect: f32,
    /// Share of 6×6 cells over that box holding ink; and their spread.
    pub cells_covered: f32,
    pub cells_cv: f32,
    /// Share of ink pixels that are saturated; and how few hues they use.
    pub ink_chroma_frac: f32,
    pub hue_top2: f32,
    /// Mean HSV saturation of the whole image.
    pub img_sat_mean: f32,
}

impl CpLikelihoodFeatures {
    /// The model's input, in [`MODEL_FEATURES`] order.
    pub fn model_vector(&self) -> [f32; MODEL_FEATURE_COUNT] {
        [
            self.bg_frac,
            self.gray_std,
            self.lattice22,
            self.top4_mass,
            self.orient_entropy,
            self.line_len_norm,
            self.long_line_ratio,
            self.endpoint_rate,
            self.junction_rate,
            self.ends_per_junction,
            self.cells_cv,
            self.cells_covered,
            self.ink_frac,
            self.img_sat_mean,
            self.diag_mass,
            self.ink_to_skel,
            self.full_span_frac,
            self.mean_seg_len_norm,
            self.periodicity,
            self.n_peaks as f32,
        ]
    }
}

/// The verdict on one image.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CpLikelihood {
    /// Model probability, 0–1.
    pub score: f32,
    /// `score >= threshold`: the offer is made.
    pub likely: bool,
    /// The operating point the model was tuned to (see `likelihood_model.rs`).
    pub threshold: f32,
    pub features: CpLikelihoodFeatures,
}

/// Score an RGBA image. Any size; it is resampled to [`LIKELIHOOD_MAX_SIDE`].
pub fn crease_pattern_likelihood(
    rgba: &[u8],
    width: u32,
    height: u32,
) -> Result<CpLikelihood, LikelihoodError> {
    debug_assert_eq!(likelihood_model::FEATURE_NAMES, MODEL_FEATURES);
    let features = extract_features(rgba, width, height)?;
    let score = score_features(&features);
    Ok(CpLikelihood {
        score,
        likely: score >= likelihood_model::THRESHOLD,
        threshold: likelihood_model::THRESHOLD,
        features,
    })
}

/// The model's probability for a feature set.
pub fn score_features(features: &CpLikelihoodFeatures) -> f32 {
    let raw = likelihood_model::raw_score(&features.model_vector());
    1.0 / (1.0 + (-raw).exp())
}

/// The features alone — what the harness fits the model on.
pub fn extract_features(
    rgba: &[u8],
    width: u32,
    height: u32,
) -> Result<CpLikelihoodFeatures, LikelihoodError> {
    if width == 0 || height == 0 {
        return Err(LikelihoodError::InvalidDimensions { width, height });
    }
    let expected = width as usize * height as usize * 4;
    if rgba.len() != expected {
        return Err(LikelihoodError::RgbaLengthMismatch {
            expected,
            actual: rgba.len(),
        });
    }
    let raster = downscale_rgba(rgba, width as usize, height as usize);
    Ok(features_of(&raster))
}

// ---------------------------------------------------------------------------
// Raster

struct Raster {
    width: usize,
    height: usize,
    r: Vec<u8>,
    g: Vec<u8>,
    b: Vec<u8>,
    luma: Vec<u8>,
}

/// Area-average resample to at most [`LIKELIHOOD_MAX_SIDE`] on the longer
/// side, compositing alpha over white (a transparent PNG background reads as
/// paper, not as black).
fn downscale_rgba(rgba: &[u8], width: usize, height: usize) -> Raster {
    let scale = (LIKELIHOOD_MAX_SIDE as f64 / width.max(height) as f64).min(1.0);
    let dw = ((width as f64 * scale).round() as usize).clamp(1, width);
    let dh = ((height as f64 * scale).round() as usize).clamp(1, height);
    let mut raster = Raster {
        width: dw,
        height: dh,
        r: vec![0; dw * dh],
        g: vec![0; dw * dh],
        b: vec![0; dw * dh],
        luma: vec![0; dw * dh],
    };
    for dy in 0..dh {
        let y0 = dy * height / dh;
        let y1 = ((dy + 1) * height / dh).max(y0 + 1).min(height);
        for dx in 0..dw {
            let x0 = dx * width / dw;
            let x1 = ((dx + 1) * width / dw).max(x0 + 1).min(width);
            let (mut sr, mut sg, mut sb, mut n) = (0u64, 0u64, 0u64, 0u64);
            for y in y0..y1 {
                let row = y * width;
                for x in x0..x1 {
                    let i = (row + x) * 4;
                    let a = rgba[i + 3] as u64;
                    let inv = 255 - a;
                    sr += (rgba[i] as u64 * a + 255 * inv) / 255;
                    sg += (rgba[i + 1] as u64 * a + 255 * inv) / 255;
                    sb += (rgba[i + 2] as u64 * a + 255 * inv) / 255;
                    n += 1;
                }
            }
            let r = (sr / n) as u8;
            let g = (sg / n) as u8;
            let b = (sb / n) as u8;
            let o = dy * dw + dx;
            raster.r[o] = r;
            raster.g[o] = g;
            raster.b[o] = b;
            raster.luma[o] = (0.299 * r as f32 + 0.587 * g as f32 + 0.114 * b as f32).round() as u8;
        }
    }
    raster
}

// ---------------------------------------------------------------------------
// Features

fn features_of(raster: &Raster) -> CpLikelihoodFeatures {
    let (w, h) = (raster.width, raster.height);
    let n_px = (w * h) as f32;
    let luma = &raster.luma;

    // --- background level and spread
    let mut hist = [0f64; 256];
    for &v in luma {
        hist[v as usize] += 1.0;
    }
    let mut smooth = [0f64; 256];
    for (i, slot) in smooth.iter_mut().enumerate() {
        let lo = i.saturating_sub(4);
        let hi = (i + 4).min(255);
        *slot = hist[lo..=hi].iter().sum::<f64>() / 9.0;
    }
    let bg = smooth
        .iter()
        .enumerate()
        .fold(
            (0usize, f64::MIN),
            |best, (i, &v)| if v > best.1 { (i, v) } else { best },
        )
        .0 as i32;
    let bg_frac = luma
        .iter()
        .filter(|&&v| (v as i32 - bg).abs() <= 12)
        .count() as f32
        / n_px;
    let mean = luma.iter().map(|&v| v as f64).sum::<f64>() / n_px as f64;
    let var = luma.iter().map(|&v| (v as f64 - mean).powi(2)).sum::<f64>() / n_px as f64;
    let gray_std = var.sqrt() as f32;

    // --- ink: local contrast against a 21 px median
    let median = {
        let img = image::GrayImage::from_raw(w as u32, h as u32, luma.clone())
            .expect("raster dimensions match its buffer");
        imageproc::filter::median_filter(&img, 10, 10).into_raw()
    };
    let ink: Vec<bool> = luma
        .iter()
        .zip(&median)
        .map(|(&v, &m)| (v as i32 - m as i32).abs() > 24)
        .collect();
    let ink_count = ink.iter().filter(|&&v| v).count();
    let ink_frac = ink_count as f32 / n_px;

    // --- edges and orientation
    let blur = gaussian3(luma, w, h);
    let (gx, gy) = sobel(&blur, w, h);
    let edges = canny(&gx, &gy, w, h, 60, 160);
    let edge_count = edges.iter().filter(|&&v| v).count();
    let edge_frac = edge_count as f32 / n_px;
    let orient = orientation_features(&gx, &gy, &edges);

    // --- straight segments
    let m = w.min(h) as f64;
    let hough = HoughLinesPConfig {
        rho: 1.0,
        theta: std::f32::consts::PI / 180.0,
        threshold: ((m * 0.03) as i32).max(20),
        min_line_length: ((m * 0.04) as i32).max(20) as f64,
        max_line_gap: 4.0,
        lines_max: i32::MAX,
    };
    let edge_u8: Vec<u8> = edges.iter().map(|&e| if e { 255 } else { 0 }).collect();
    let segments = hough_lines_p_opencv_cpu(&edge_u8, w, h, &hough).unwrap_or_default();
    let mut line_map = vec![false; w * h];
    let mut total_len = 0.0f64;
    let mut full_span_len = 0.0f64;
    for segment in &segments {
        draw_thick_segment(
            &mut line_map,
            w,
            h,
            (segment.x1, segment.y1),
            (segment.x2, segment.y2),
        );
        let len = (((segment.x2 - segment.x1) as f64).powi(2)
            + ((segment.y2 - segment.y1) as f64).powi(2))
        .sqrt();
        total_len += len;
        if len >= 0.75 * m {
            full_span_len += len;
        }
    }
    let covered_edges = line_map
        .iter()
        .zip(&edges)
        .filter(|&(&l, &e)| l && e)
        .count();
    let n_lines = segments.len() as u32;
    let line_len_norm = (total_len / m) as f32;
    let long_line_ratio = covered_edges as f32 / edge_count.max(1) as f32;
    let full_span_frac = if total_len > 0.0 {
        (full_span_len / total_len) as f32
    } else {
        0.0
    };
    let mean_seg_len_norm = if segments.is_empty() {
        0.0
    } else {
        (total_len / segments.len() as f64 / m) as f32
    };

    // --- periodicity of the ink projections
    let periodicity = {
        let mut cols = vec![0f64; w];
        let mut rows = vec![0f64; h];
        for y in 0..h {
            for x in 0..w {
                if ink[y * w + x] {
                    cols[x] += 1.0;
                    rows[y] += 1.0;
                }
            }
        }
        profile_periodicity(&cols).max(profile_periodicity(&rows))
    };

    // --- skeleton statistics
    let (
        skel_px_frac,
        endpoint_rate,
        junction_rate,
        ends_per_junction,
        n_endpoints,
        n_junctions,
        ink_to_skel,
    ) = if ink_frac > 0.0005 && ink_frac < 0.6 {
        let skeleton = zhang_suen(&ink, w, h);
        let stats = skeleton_stats(&skeleton, w, h);
        let sp = stats.pixels as f32;
        (
            sp / n_px,
            stats.endpoints as f32 / sp.max(1.0),
            stats.junctions as f32 / sp.max(1.0),
            stats.endpoints as f32 / (stats.junctions as f32).max(1.0),
            stats.endpoints as u32,
            stats.junctions as u32,
            ink_count as f32 / sp.max(1.0),
        )
    } else {
        (0.0, 1.0, 0.0, 99.0, 0, 0, 99.0)
    };

    // --- coverage uniformity over the ink's own box
    let (ink_bbox_fill, ink_bbox_aspect, cells_covered, cells_cv) = coverage(&ink, w, h);

    // --- colour
    let (ink_chroma_frac, hue_top2, img_sat_mean) = colour_features(raster, &ink);

    CpLikelihoodFeatures {
        width: w as u32,
        height: h as u32,
        aspect: w.max(h) as f32 / w.min(h).max(1) as f32,
        bg_frac,
        gray_std,
        ink_frac,
        edge_frac,
        top4_mass: orient.top4_mass,
        n_peaks: orient.n_peaks,
        lattice22: orient.lattice22,
        lattice45: orient.lattice45,
        lattice90: orient.lattice90,
        diag_mass: orient.diag_mass,
        axis_mass: orient.axis_mass,
        orient_entropy: orient.entropy,
        n_lines,
        line_len_norm,
        long_line_ratio,
        full_span_frac,
        mean_seg_len_norm,
        periodicity,
        skel_px_frac,
        endpoint_rate,
        junction_rate,
        ends_per_junction,
        n_endpoints,
        n_junctions,
        ink_to_skel,
        ink_bbox_fill,
        ink_bbox_aspect,
        cells_covered,
        cells_cv,
        ink_chroma_frac,
        hue_top2,
        img_sat_mean,
    }
}

// ---------------------------------------------------------------------------
// Edges

/// 3×3 binomial blur, borders replicated.
fn gaussian3(luma: &[u8], w: usize, h: usize) -> Vec<u8> {
    let at = |x: isize, y: isize| -> u32 {
        let xc = x.clamp(0, w as isize - 1) as usize;
        let yc = y.clamp(0, h as isize - 1) as usize;
        luma[yc * w + xc] as u32
    };
    let mut out = vec![0u8; w * h];
    for y in 0..h as isize {
        for x in 0..w as isize {
            let sum = at(x - 1, y - 1)
                + 2 * at(x, y - 1)
                + at(x + 1, y - 1)
                + 2 * at(x - 1, y)
                + 4 * at(x, y)
                + 2 * at(x + 1, y)
                + at(x - 1, y + 1)
                + 2 * at(x, y + 1)
                + at(x + 1, y + 1);
            out[y as usize * w + x as usize] = ((sum + 8) / 16) as u8;
        }
    }
    out
}

/// 3×3 Sobel, borders replicated, unnormalised like OpenCV's.
fn sobel(img: &[u8], w: usize, h: usize) -> (Vec<i32>, Vec<i32>) {
    let at = |x: isize, y: isize| -> i32 {
        let xc = x.clamp(0, w as isize - 1) as usize;
        let yc = y.clamp(0, h as isize - 1) as usize;
        img[yc * w + xc] as i32
    };
    let mut gx = vec![0i32; w * h];
    let mut gy = vec![0i32; w * h];
    for y in 0..h as isize {
        for x in 0..w as isize {
            let o = y as usize * w + x as usize;
            gx[o] = -at(x - 1, y - 1) + at(x + 1, y - 1) - 2 * at(x - 1, y) + 2 * at(x + 1, y)
                - at(x - 1, y + 1)
                + at(x + 1, y + 1);
            gy[o] = -at(x - 1, y - 1) - 2 * at(x, y - 1) - at(x + 1, y - 1)
                + at(x - 1, y + 1)
                + 2 * at(x, y + 1)
                + at(x + 1, y + 1);
        }
    }
    (gx, gy)
}

/// Canny on precomputed gradients: L1 magnitude, OpenCV's four-direction
/// non-maximum suppression, hysteresis from the strong pixels outward.
fn canny(gx: &[i32], gy: &[i32], w: usize, h: usize, low: i32, high: i32) -> Vec<bool> {
    const SHIFT: i32 = 15;
    const TG22: i64 = 13_573; // tan(22.5°) << SHIFT
    let mag: Vec<i32> = gx
        .iter()
        .zip(gy)
        .map(|(&x, &y)| x.abs() + y.abs())
        .collect();
    let at = |x: isize, y: isize| -> i32 {
        if x < 0 || y < 0 || x >= w as isize || y >= h as isize {
            0
        } else {
            mag[y as usize * w + x as usize]
        }
    };
    // 0 = not an edge, 1 = passed suppression and the low threshold, 2 = edge
    let mut state = vec![0u8; w * h];
    let mut stack = Vec::new();
    for y in 0..h as isize {
        for x in 0..w as isize {
            let o = y as usize * w + x as usize;
            let m = mag[o];
            if m <= low {
                continue;
            }
            let xs = gx[o] as i64;
            let ys = gy[o] as i64;
            let ax = xs.abs();
            let ay = ys.abs() << SHIFT;
            let tg22x = ax * TG22;
            let keep = if ay < tg22x {
                m > at(x - 1, y) && m >= at(x + 1, y)
            } else {
                let tg67x = tg22x + (ax << (SHIFT + 1));
                if ay > tg67x {
                    m > at(x, y - 1) && m >= at(x, y + 1)
                } else {
                    let s: isize = if (xs ^ ys) < 0 { -1 } else { 1 };
                    m > at(x - s, y - 1) && m > at(x + s, y + 1)
                }
            };
            if !keep {
                continue;
            }
            if m > high {
                state[o] = 2;
                stack.push(o);
            } else {
                state[o] = 1;
            }
        }
    }
    while let Some(o) = stack.pop() {
        let x = (o % w) as isize;
        let y = (o / w) as isize;
        for dy in -1..=1 {
            for dx in -1..=1 {
                let nx = x + dx;
                let ny = y + dy;
                if nx < 0 || ny < 0 || nx >= w as isize || ny >= h as isize {
                    continue;
                }
                let no = ny as usize * w + nx as usize;
                if state[no] == 1 {
                    state[no] = 2;
                    stack.push(no);
                }
            }
        }
    }
    state.into_iter().map(|s| s == 2).collect()
}

// ---------------------------------------------------------------------------
// Orientation histogram

struct Orientation {
    top4_mass: f32,
    n_peaks: u32,
    lattice22: f32,
    lattice45: f32,
    lattice90: f32,
    diag_mass: f32,
    axis_mass: f32,
    entropy: f32,
}

/// Mass within `halfwidth` degrees of each centre, each bin counted once.
fn peak_mass(hist: &[f64; 180], centres: &[f64], halfwidth: f64) -> f64 {
    let mut used = [false; 180];
    let mut mass = 0.0;
    for &c in centres {
        let lo = (c - halfwidth).floor() as i64;
        let hi = (c + halfwidth).ceil() as i64;
        for i in lo..=hi {
            let idx = i.rem_euclid(180) as usize;
            if !used[idx] {
                used[idx] = true;
                mass += hist[idx];
            }
        }
    }
    mass
}

fn orientation_features(gx: &[i32], gy: &[i32], edges: &[bool]) -> Orientation {
    let mut hist = [0f64; 180];
    let mut count = 0usize;
    for (o, &edge) in edges.iter().enumerate() {
        if !edge {
            continue;
        }
        count += 1;
        let x = gx[o] as f64;
        let y = gy[o] as f64;
        let angle = (y.atan2(x).to_degrees() + 180.0).rem_euclid(180.0);
        let bin = (angle.floor() as i64).rem_euclid(180) as usize;
        hist[bin] += (x * x + y * y).sqrt();
    }
    if count < 50 {
        return Orientation {
            top4_mass: 0.0,
            n_peaks: 0,
            lattice22: 0.0,
            lattice45: 0.0,
            lattice90: 0.0,
            diag_mass: 0.0,
            axis_mass: 0.0,
            entropy: 1.0,
        };
    }
    let mut smooth = [0f64; 180];
    for i in 0..180 {
        smooth[i] = (hist[(i + 179) % 180] + 2.0 * hist[i] + hist[(i + 1) % 180]) / 4.0;
    }
    let hist = smooth;
    let total = hist.iter().sum::<f64>() + 1e-9;
    let entropy = -hist
        .iter()
        .filter(|&&v| v > 0.0)
        .map(|&v| {
            let p = v / total;
            p * p.ln()
        })
        .sum::<f64>()
        / 180f64.ln();

    let mut peaks: Vec<usize> = (0..180)
        .filter(|&i| hist[i] >= hist[(i + 179) % 180] && hist[i] > hist[(i + 1) % 180])
        .collect();
    peaks.sort_by(|&a, &b| hist[b].total_cmp(&hist[a]));
    let mut chosen: Vec<usize> = Vec::new();
    for i in peaks {
        let apart = chosen.iter().all(|&j| {
            let d = (i as i64 - j as i64).abs();
            d.min(180 - d) >= 6
        });
        if apart {
            chosen.push(i);
        }
        if chosen.len() >= 8 {
            break;
        }
    }
    let top: Vec<f64> = chosen.iter().take(4).map(|&i| i as f64).collect();
    let top4_mass = peak_mass(&hist, &top, 3.0) / total;
    let n_peaks = chosen
        .iter()
        .filter(|&&i| peak_mass(&hist, &[i as f64], 3.0) / total >= 0.04)
        .count() as u32;

    let sweep = |period: f64, count: usize| -> (f64, f64) {
        let mut best = 0.0;
        let mut best_phi = 0.0;
        let steps = (period / 0.5) as usize;
        for step in 0..steps {
            let phi = step as f64 * 0.5;
            let centres: Vec<f64> = (0..count).map(|k| phi + k as f64 * period).collect();
            let mass = peak_mass(&hist, &centres, 2.5) / total;
            if mass > best {
                best = mass;
                best_phi = phi;
            }
        }
        (best, best_phi)
    };
    let (lattice22, best_phi) = sweep(22.5, 8);
    let (lattice45, _) = sweep(45.0, 4);
    let (lattice90, _) = sweep(90.0, 2);

    let axis_masses: Vec<f64> = (0..8)
        .map(|k| {
            peak_mass(
                &hist,
                &[(best_phi + k as f64 * 22.5).rem_euclid(180.0)],
                2.5,
            ) / total
        })
        .collect();
    let k0 = axis_masses
        .iter()
        .enumerate()
        .fold(
            (0usize, f64::MIN),
            |best, (i, &v)| if v > best.1 { (i, v) } else { best },
        )
        .0;
    let axis_mass = axis_masses[k0] + axis_masses[(k0 + 4) % 8];
    let diag_mass = axis_masses[(k0 + 2) % 8] + axis_masses[(k0 + 6) % 8];

    Orientation {
        top4_mass: top4_mass as f32,
        n_peaks,
        lattice22: lattice22 as f32,
        lattice45: lattice45 as f32,
        lattice90: lattice90 as f32,
        diag_mass: diag_mass as f32,
        axis_mass: axis_mass as f32,
        entropy: entropy as f32,
    }
}

// ---------------------------------------------------------------------------
// Segments

/// Mark a segment 3 px wide: Bresenham along it, a 3×3 stamp at each step.
fn draw_thick_segment(map: &mut [bool], w: usize, h: usize, a: (i32, i32), b: (i32, i32)) {
    let (mut x, mut y) = a;
    let (x1, y1) = b;
    let dx = (x1 - x).abs();
    let dy = -(y1 - y).abs();
    let sx = if x < x1 { 1 } else { -1 };
    let sy = if y < y1 { 1 } else { -1 };
    let mut err = dx + dy;
    loop {
        for oy in -1..=1 {
            for ox in -1..=1 {
                let px = x + ox;
                let py = y + oy;
                if px >= 0 && py >= 0 && (px as usize) < w && (py as usize) < h {
                    map[py as usize * w + px as usize] = true;
                }
            }
        }
        if x == x1 && y == y1 {
            break;
        }
        let e2 = 2 * err;
        if e2 >= dy {
            err += dy;
            x += sx;
        }
        if e2 <= dx {
            err += dx;
            y += sy;
        }
    }
}

/// Peak of the normalised autocorrelation at lags between 4 and a third of the
/// profile: periodic ink (graph paper, bricks, blinds) scores near 1.
fn profile_periodicity(profile: &[f64]) -> f32 {
    let n = profile.len();
    if n < 32 {
        return 0.0;
    }
    let mean = profile.iter().sum::<f64>() / n as f64;
    let centred: Vec<f64> = profile.iter().map(|v| v - mean).collect();
    if centred.iter().map(|v| v.abs()).sum::<f64>() < 1e-6 {
        return 0.0;
    }
    let ac0: f64 = centred.iter().map(|v| v * v).sum::<f64>().max(1e-9);
    let hi = (n / 3).max(5);
    let mut best = f64::MIN;
    for lag in 4..hi {
        let ac: f64 = centred[..n - lag]
            .iter()
            .zip(&centred[lag..])
            .map(|(a, b)| a * b)
            .sum();
        best = best.max(ac / ac0);
    }
    best as f32
}

// ---------------------------------------------------------------------------
// Skeleton

/// Zhang–Suen thinning; deletions within a sub-iteration are simultaneous.
fn zhang_suen(mask: &[bool], w: usize, h: usize) -> Vec<bool> {
    let pw = w + 2;
    let mut img = vec![0u8; pw * (h + 2)];
    for y in 0..h {
        for x in 0..w {
            img[(y + 1) * pw + x + 1] = mask[y * w + x] as u8;
        }
    }
    let mut remove = Vec::new();
    for _ in 0..60 {
        let mut changed = false;
        for step in 0..2 {
            remove.clear();
            for y in 1..=h {
                for x in 1..=w {
                    let o = y * pw + x;
                    if img[o] == 0 {
                        continue;
                    }
                    let p2 = img[o - pw];
                    let p3 = img[o - pw + 1];
                    let p4 = img[o + 1];
                    let p5 = img[o + pw + 1];
                    let p6 = img[o + pw];
                    let p7 = img[o + pw - 1];
                    let p8 = img[o - 1];
                    let p9 = img[o - pw - 1];
                    let b = p2 + p3 + p4 + p5 + p6 + p7 + p8 + p9;
                    if !(2..=6).contains(&b) {
                        continue;
                    }
                    let seq = [p2, p3, p4, p5, p6, p7, p8, p9, p2];
                    let a = seq
                        .windows(2)
                        .filter(|pair| pair[0] == 0 && pair[1] == 1)
                        .count();
                    if a != 1 {
                        continue;
                    }
                    let (c1, c2) = if step == 0 {
                        (p2 * p4 * p6 == 0, p4 * p6 * p8 == 0)
                    } else {
                        (p2 * p4 * p8 == 0, p2 * p6 * p8 == 0)
                    };
                    if c1 && c2 {
                        remove.push(o);
                    }
                }
            }
            if !remove.is_empty() {
                changed = true;
                for &o in &remove {
                    img[o] = 0;
                }
            }
        }
        if !changed {
            break;
        }
    }
    let mut out = vec![false; w * h];
    for y in 0..h {
        for x in 0..w {
            out[y * w + x] = img[(y + 1) * pw + x + 1] == 1;
        }
    }
    out
}

struct SkeletonStats {
    pixels: usize,
    /// Crossing number 1.
    endpoints: usize,
    /// 8-connected clusters of pixels with crossing number ≥ 3 — a thick
    /// crossing is one junction, not four.
    junctions: usize,
}

fn skeleton_stats(skeleton: &[bool], w: usize, h: usize) -> SkeletonStats {
    let at = |x: isize, y: isize| -> u8 {
        if x < 0 || y < 0 || x >= w as isize || y >= h as isize {
            0
        } else {
            skeleton[y as usize * w + x as usize] as u8
        }
    };
    let mut pixels = 0;
    let mut endpoints = 0;
    let mut junction_px = vec![false; w * h];
    for y in 0..h as isize {
        for x in 0..w as isize {
            if !skeleton[y as usize * w + x as usize] {
                continue;
            }
            pixels += 1;
            let ring = [
                at(x, y - 1),
                at(x + 1, y - 1),
                at(x + 1, y),
                at(x + 1, y + 1),
                at(x, y + 1),
                at(x - 1, y + 1),
                at(x - 1, y),
                at(x - 1, y - 1),
            ];
            let crossings = (0..8)
                .filter(|&i| ring[i] == 0 && ring[(i + 1) % 8] == 1)
                .count();
            if crossings == 1 {
                endpoints += 1;
            } else if crossings >= 3 {
                junction_px[y as usize * w + x as usize] = true;
            }
        }
    }
    // 8-connected components of the junction pixels
    let mut seen = vec![false; w * h];
    let mut junctions = 0;
    let mut stack = Vec::new();
    for start in 0..w * h {
        if !junction_px[start] || seen[start] {
            continue;
        }
        junctions += 1;
        seen[start] = true;
        stack.push(start);
        while let Some(o) = stack.pop() {
            let x = (o % w) as isize;
            let y = (o / w) as isize;
            for dy in -1..=1 {
                for dx in -1..=1 {
                    let nx = x + dx;
                    let ny = y + dy;
                    if nx < 0 || ny < 0 || nx >= w as isize || ny >= h as isize {
                        continue;
                    }
                    let no = ny as usize * w + nx as usize;
                    if junction_px[no] && !seen[no] {
                        seen[no] = true;
                        stack.push(no);
                    }
                }
            }
        }
    }
    SkeletonStats {
        pixels,
        endpoints,
        junctions,
    }
}

// ---------------------------------------------------------------------------
// Coverage and colour

fn percentile_sorted(values: &[u32], p: f64) -> f64 {
    if values.is_empty() {
        return 0.0;
    }
    let pos = p * (values.len() - 1) as f64;
    let lo = pos.floor() as usize;
    let hi = pos.ceil() as usize;
    let frac = pos - lo as f64;
    values[lo] as f64 * (1.0 - frac) + values[hi] as f64 * frac
}

/// `(ink_bbox_fill, ink_bbox_aspect, cells_covered, cells_cv)`.
fn coverage(ink: &[bool], w: usize, h: usize) -> (f32, f32, f32, f32) {
    let mut xs = Vec::new();
    let mut ys = Vec::new();
    for y in 0..h {
        for x in 0..w {
            if ink[y * w + x] {
                xs.push(x as u32);
                ys.push(y as u32);
            }
        }
    }
    if xs.len() <= 20 {
        return (0.0, 1.0, 0.0, 9.0);
    }
    let mut sx = xs.clone();
    let mut sy = ys.clone();
    sx.sort_unstable();
    sy.sort_unstable();
    let x0 = percentile_sorted(&sx, 0.01);
    let x1 = percentile_sorted(&sx, 0.99);
    let y0 = percentile_sorted(&sy, 0.01);
    let y1 = percentile_sorted(&sy, 0.99);
    let bw = (x1 - x0).max(1.0);
    let bh = (y1 - y0).max(1.0);
    const G: usize = 6;
    let mut cells = [0f64; G * G];
    for (&x, &y) in xs.iter().zip(&ys) {
        let cx = (((x as f64 - x0) / bw * G as f64) as i64).clamp(0, G as i64 - 1) as usize;
        let cy = (((y as f64 - y0) / bh * G as f64) as i64).clamp(0, G as i64 - 1) as usize;
        cells[cy * G + cx] += 1.0;
    }
    let cell_area = bw * bh / (G * G) as f64;
    for cell in cells.iter_mut() {
        *cell /= cell_area;
    }
    let covered = cells.iter().filter(|&&c| c > 0.01).count() as f64 / (G * G) as f64;
    let mean = cells.iter().sum::<f64>() / (G * G) as f64;
    let var = cells.iter().map(|c| (c - mean).powi(2)).sum::<f64>() / (G * G) as f64;
    let cv = var.sqrt() / (mean + 1e-9);
    (
        (bw * bh / (w * h) as f64) as f32,
        (bw.max(bh) / bw.min(bh)) as f32,
        covered as f32,
        cv as f32,
    )
}

/// OpenCV-style HSV: hue 0–179, saturation and value 0–255.
fn hsv(r: u8, g: u8, b: u8) -> (u8, u8, u8) {
    let (r, g, b) = (r as f32, g as f32, b as f32);
    let max = r.max(g).max(b);
    let min = r.min(g).min(b);
    let v = max;
    let s = if max > 0.0 {
        255.0 * (max - min) / max
    } else {
        0.0
    };
    let h = if max == min {
        0.0
    } else if max == r {
        60.0 * (g - b) / (max - min)
    } else if max == g {
        120.0 + 60.0 * (b - r) / (max - min)
    } else {
        240.0 + 60.0 * (r - g) / (max - min)
    };
    let h = if h < 0.0 { h + 360.0 } else { h };
    (
        (h / 2.0).round() as u8 % 180,
        s.round() as u8,
        v.round() as u8,
    )
}

/// `(ink_chroma_frac, hue_top2, img_sat_mean)`.
fn colour_features(raster: &Raster, ink: &[bool]) -> (f32, f32, f32) {
    let n = raster.width * raster.height;
    let mut sat_sum = 0u64;
    let mut ink_n = 0usize;
    let mut chroma_n = 0usize;
    let mut hues = [0u32; 18];
    for (((&r, &g), &b), &is_ink) in raster.r.iter().zip(&raster.g).zip(&raster.b).zip(ink) {
        let (hue, s, v) = hsv(r, g, b);
        sat_sum += s as u64;
        if is_ink {
            ink_n += 1;
            if s > 90 && v > 50 {
                chroma_n += 1;
                hues[(hue / 10).min(17) as usize] += 1;
            }
        }
    }
    let img_sat_mean = sat_sum as f32 / n as f32 / 255.0;
    if ink_n <= 20 {
        return (0.0, 1.0, img_sat_mean);
    }
    let chroma_frac = chroma_n as f32 / ink_n as f32;
    let hue_top2 = if chroma_n > 20 {
        let mut sorted = hues;
        sorted.sort_unstable();
        (sorted[16] + sorted[17]) as f32 / chroma_n as f32
    } else {
        1.0
    };
    (chroma_frac, hue_top2, img_sat_mean)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rgba_from_luma(luma: &[u8], w: usize, h: usize) -> Vec<u8> {
        let mut out = Vec::with_capacity(w * h * 4);
        for &v in luma {
            out.extend_from_slice(&[v, v, v, 255]);
        }
        out
    }

    /// An anti-aliased ~1.5 px line, like a renderer or a canvas downscale
    /// produces: coverage from the distance to the segment, so gradient
    /// orientations sit on the line's normal rather than on staircase steps.
    fn line(luma: &mut [u8], w: usize, h: usize, a: (f64, f64), b: (f64, f64), value: u8) {
        let (dx, dy) = (b.0 - a.0, b.1 - a.1);
        let len2 = (dx * dx + dy * dy).max(1e-9);
        let x_lo = (a.0.min(b.0) - 2.0).floor().max(0.0) as usize;
        let x_hi = ((a.0.max(b.0) + 2.0).ceil() as usize).min(w - 1);
        let y_lo = (a.1.min(b.1) - 2.0).floor().max(0.0) as usize;
        let y_hi = ((a.1.max(b.1) + 2.0).ceil() as usize).min(h - 1);
        for y in y_lo..=y_hi {
            for x in x_lo..=x_hi {
                let (px, py) = (x as f64, y as f64);
                let t = (((px - a.0) * dx + (py - a.1) * dy) / len2).clamp(0.0, 1.0);
                let (cx, cy) = (a.0 + dx * t, a.1 + dy * t);
                let dist = ((px - cx).powi(2) + (py - cy).powi(2)).sqrt();
                let coverage = (1.25 - dist).clamp(0.0, 1.0);
                let target = value as f64 + (255.0 - value as f64) * (1.0 - coverage);
                let slot = &mut luma[y * w + x];
                *slot = (*slot).min(target.round() as u8);
            }
        }
    }

    #[test]
    fn model_feature_names_match_the_generated_table() {
        assert_eq!(likelihood_model::FEATURE_NAMES, MODEL_FEATURES);
    }

    #[test]
    fn thinning_keeps_a_cross_as_four_ends_and_one_junction() {
        let (w, h) = (60, 60);
        let mut mask = vec![false; w * h];
        for y in 0..h {
            for x in 0..w {
                let on_h = (y as i32 - 30).abs() <= 1 && (5..55).contains(&x);
                let on_v = (x as i32 - 30).abs() <= 1 && (5..55).contains(&y);
                mask[y * w + x] = on_h || on_v;
            }
        }
        let skeleton = zhang_suen(&mask, w, h);
        let stats = skeleton_stats(&skeleton, w, h);
        assert_eq!(stats.endpoints, 4);
        assert_eq!(stats.junctions, 1);
        assert!(stats.pixels < mask.iter().filter(|&&v| v).count());
    }

    #[test]
    fn orientation_lattice_reads_a_star_of_lattice_angles() {
        let (w, h) = (256usize, 256usize);
        let mut luma = vec![255u8; w * h];
        for k in 0..8 {
            let angle = (k as f64 * 22.5).to_radians();
            let (dx, dy) = (angle.cos() * 120.0, angle.sin() * 120.0);
            line(
                &mut luma,
                w,
                h,
                (128.0 - dx, 128.0 - dy),
                (128.0 + dx, 128.0 + dy),
                0,
            );
        }
        let f = extract_features(&rgba_from_luma(&luma, w, h), w as u32, h as u32).unwrap();
        assert!(f.lattice22 > 0.85, "lattice22 {}", f.lattice22);
        assert!(f.diag_mass > 0.1, "diag_mass {}", f.diag_mass);
        assert_eq!(f.n_peaks, 8);
    }

    #[test]
    fn a_grid_is_all_full_span_segments_and_periodic() {
        let (w, h) = (300usize, 300usize);
        let mut luma = vec![255u8; w * h];
        for i in (10..300).step_by(25) {
            line(&mut luma, w, h, (i as f64, 0.0), (i as f64, 299.0), 0);
            line(&mut luma, w, h, (0.0, i as f64), (299.0, i as f64), 0);
        }
        let f = extract_features(&rgba_from_luma(&luma, w, h), w as u32, h as u32).unwrap();
        assert!(
            f.full_span_frac > 0.9,
            "full_span_frac {}",
            f.full_span_frac
        );
        assert!(f.periodicity > 0.5, "periodicity {}", f.periodicity);
        assert!(f.endpoint_rate < 0.05, "endpoint_rate {}", f.endpoint_rate);
    }

    #[test]
    fn a_crease_pattern_has_almost_no_dangling_ends() {
        let (w, h) = (400usize, 400usize);
        let mut luma = vec![255u8; w * h];
        // paper, diagonals, a few creases ending on others
        line(&mut luma, w, h, (20.0, 20.0), (380.0, 20.0), 0);
        line(&mut luma, w, h, (380.0, 20.0), (380.0, 380.0), 0);
        line(&mut luma, w, h, (380.0, 380.0), (20.0, 380.0), 0);
        line(&mut luma, w, h, (20.0, 380.0), (20.0, 20.0), 0);
        line(&mut luma, w, h, (20.0, 20.0), (380.0, 380.0), 0);
        line(&mut luma, w, h, (380.0, 20.0), (20.0, 380.0), 0);
        line(&mut luma, w, h, (200.0, 20.0), (200.0, 380.0), 0);
        line(&mut luma, w, h, (20.0, 200.0), (380.0, 200.0), 0);
        line(&mut luma, w, h, (20.0, 20.0), (200.0, 94.6), 0);
        line(&mut luma, w, h, (380.0, 380.0), (200.0, 305.4), 0);
        let f = extract_features(&rgba_from_luma(&luma, w, h), w as u32, h as u32).unwrap();
        assert!(f.endpoint_rate < 0.02, "endpoint_rate {}", f.endpoint_rate);
        assert!(
            f.long_line_ratio > 0.7,
            "long_line_ratio {}",
            f.long_line_ratio
        );
        assert!(f.bg_frac > 0.9);
    }

    #[test]
    fn text_like_dashes_are_mostly_endpoints() {
        let (w, h) = (400usize, 400usize);
        let mut luma = vec![255u8; w * h];
        let mut seed = 7u32;
        for row in 0..14 {
            let y = 30.0 + row as f64 * 26.0;
            let mut x = 30.0;
            while x < 360.0 {
                seed = seed.wrapping_mul(1_103_515_245).wrapping_add(12_345);
                let len = 6.0 + (seed >> 16) as f64 % 18.0;
                line(&mut luma, w, h, (x, y), (x + len, y), 0);
                line(&mut luma, w, h, (x, y - 6.0), (x, y), 0);
                x += len + 8.0;
            }
        }
        let f = extract_features(&rgba_from_luma(&luma, w, h), w as u32, h as u32).unwrap();
        assert!(f.endpoint_rate > 0.05, "endpoint_rate {}", f.endpoint_rate);
    }

    fn verdict_of(luma: &[u8], w: usize, h: usize) -> CpLikelihood {
        crease_pattern_likelihood(&rgba_from_luma(luma, w, h), w as u32, h as u32).unwrap()
    }

    #[test]
    fn a_clean_render_is_offered() {
        let png = include_bytes!("../tests/fixtures/cp-detect-oracle/clean-smoke.input.png");
        let img = image::load_from_memory(png).unwrap().to_rgba8();
        let (w, h) = img.dimensions();
        let verdict = crease_pattern_likelihood(img.as_raw(), w, h).unwrap();
        assert!(verdict.likely, "score {}", verdict.score);
        assert!(verdict.score > 0.9, "score {}", verdict.score);
    }

    #[test]
    fn a_dark_background_render_is_offered() {
        let png = include_bytes!("../tests/fixtures/cp-detect-oracle/clean-smoke.input.png");
        let img = image::load_from_memory(png).unwrap().to_rgba8();
        let (w, h) = img.dimensions();
        let inverted: Vec<u8> = img
            .as_raw()
            .chunks_exact(4)
            .flat_map(|px| [255 - px[0], 255 - px[1], 255 - px[2], 255])
            .collect();
        let verdict = crease_pattern_likelihood(&inverted, w, h).unwrap();
        assert!(verdict.likely, "score {}", verdict.score);
    }

    #[test]
    fn blank_and_noise_and_text_are_not_offered() {
        let (w, h) = (400usize, 400usize);
        let blank = vec![255u8; w * h];
        let v = verdict_of(&blank, w, h);
        assert!(!v.likely, "blank scored {}", v.score);

        // value noise with smooth blobs: a photograph's texture, no straight lines
        let mut seed = 12345u32;
        let mut coarse = vec![0f32; 20 * 20];
        for cell in coarse.iter_mut() {
            seed = seed.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            *cell = (seed >> 8) as f32 / (1u32 << 24) as f32;
        }
        let mut noise = vec![0u8; w * h];
        for y in 0..h {
            for x in 0..w {
                let fx = x as f32 / w as f32 * 19.0;
                let fy = y as f32 / h as f32 * 19.0;
                let (x0, y0) = (fx.floor() as usize, fy.floor() as usize);
                let (tx, ty) = (fx - x0 as f32, fy - y0 as f32);
                let c = |i: usize, j: usize| coarse[j.min(19) * 20 + i.min(19)];
                let v = c(x0, y0) * (1.0 - tx) * (1.0 - ty)
                    + c(x0 + 1, y0) * tx * (1.0 - ty)
                    + c(x0, y0 + 1) * (1.0 - tx) * ty
                    + c(x0 + 1, y0 + 1) * tx * ty;
                seed = seed.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
                let grain = ((seed >> 24) as f32 - 128.0) * 0.15;
                noise[y * w + x] = (v * 200.0 + 30.0 + grain).clamp(0.0, 255.0) as u8;
            }
        }
        let v = verdict_of(&noise, w, h);
        assert!(!v.likely, "noise scored {}", v.score);

        let mut text = vec![255u8; w * h];
        let mut seed = 7u32;
        for row in 0..14 {
            let y = 30.0 + row as f64 * 26.0;
            let mut x = 30.0;
            while x < 360.0 {
                seed = seed.wrapping_mul(1_103_515_245).wrapping_add(12_345);
                let len = 6.0 + (seed >> 16) as f64 % 18.0;
                line(&mut text, w, h, (x, y), (x + len, y), 0);
                line(&mut text, w, h, (x, y - 6.0), (x, y), 0);
                x += len + 8.0;
            }
        }
        let v = verdict_of(&text, w, h);
        assert!(!v.likely, "text scored {}", v.score);
    }

    #[test]
    fn rejects_bad_dimensions() {
        assert!(matches!(
            extract_features(&[0; 8], 0, 1),
            Err(LikelihoodError::InvalidDimensions { .. })
        ));
        assert!(matches!(
            extract_features(&[0; 8], 2, 2),
            Err(LikelihoodError::RgbaLengthMismatch { .. })
        ));
    }

    #[test]
    fn downscale_composites_alpha_over_white_and_caps_the_side() {
        let (w, h) = (1024usize, 512usize);
        let rgba = vec![0u8; w * h * 4]; // black, fully transparent
        let raster = downscale_rgba(&rgba, w, h);
        assert_eq!((raster.width, raster.height), (512, 256));
        assert!(raster.luma.iter().all(|&v| v == 255));
    }
}
