// @generated by `npm run generate:oriedita-defaults` (apps/web/scripts/generate-oriedita-defaults.mjs).
// Source of truth: third_party/oriedita/oriedita/src/main/resources/hotkey.properties
// DO NOT EDIT BY HAND — re-run the script instead. orieditaDefaultHotkeys.test.ts re-reads the
// vendored file and fails if this snapshot has drifted from it.
//
// Oriedita's shipped defaults for the actions that ship *with* a binding. 34 of 232
// actions are bound upstream; the rest ship unbound and are omitted, since an empty default
// says nothing. Values are Java `KeyStroke` strings, parsed by parseKeyStroke.ts.

export const ORIEDITA_DEFAULT_HOTKEYS: Readonly<Record<string, string>> = {
  'lengthenCrease2Action': 'E',
  'angleBisectorAction': 'B',
  'rabbitEarAction': 'ctrl B',
  'perpendicularDrawAction': 'P',
  'symmetricDrawAction': 'R',
  'continuousSymmetricDrawAction': 'ctrl R',
  'foldableLineDrawAction': 'N',
  'fishBoneDrawAction': 'G',
  'doubleSymmetricDrawAction': 'ctrl G',
  'reflectAction': 'ctrl M',
  'selectAllAction': 'ctrl A',
  'deleteSelectedLineSegmentAction': 'DELETE',
  'senbun_henkan2Action': 'C',
  'v_del_allAction': 'ctrl shift V',
  'colRedAction': 'M',
  'colBlueAction': 'V',
  'colBlackAction': 'L',
  'gridConfigureAction': 'G',
  'undoAction': 'ctrl Z',
  'redoAction': 'ctrl shift Z',
  'foldAction': 'F',
  'foldedFigureFlipAction': 'ctrl alt F',
  'haltAction': 'ESCAPE',
  'foldedFigureTrashAction': 'ctrl F',
  'newAction': 'ctrl N',
  'openAction': 'ctrl O',
  'saveAction': 'ctrl S',
  'saveAsAction': 'ctrl alt S',
  'prefAction': 'ctrl shift P',
  'exitAction': 'ctrl Q',
  'copyClipboardAction': 'ctrl C',
  'cutClipboardAction': 'ctrl X',
  'pasteClipboardAction': 'ctrl V',
  'pasteOffsetClipboardAction': 'ctrl shift V',
};
