use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PortStatus {
    Unsupported,
    Porting,
    UnitTested,
    OracleTested,
    DocumentedDifference,
    UpstreamGap,
    OutOfScopeUi,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PortArea {
    Model,
    Io,
    Engine,
    Data,
    Math,
    Sweep,
    Tree,
    Layout,
    Optimizer,
    Wasm,
    Oracle,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct PortDescriptor {
    pub upstream: &'static str,
    pub target: &'static str,
    pub area: PortArea,
    pub status: PortStatus,
}

pub const PORT_DESCRIPTORS: &[PortDescriptor] = &[
    PortDescriptor {
        upstream: "src/shared/json/*",
        target: "model, io::bps",
        area: PortArea::Model,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/patches/*",
        target: "io::migrations",
        area: PortArea::Io,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/app/services/importService.ts",
        target: "io::bps, io::bpz",
        area: PortArea::Io,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/app/services/exportService.ts",
        target: "io::bps, io::bpz",
        area: PortArea::Io,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/plugins/cp/*",
        target: "io::cp::{export_project, export_project_with_graphics, project_line_components}, io::fold_export",
        area: PortArea::Io,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/client/plugins/treeMaker/*",
        target: "io::treemaker_import",
        area: PortArea::Io,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/plugins/optimizer/*",
        target: "optimizer::{create_optimizer_request, write_to_template, check_optimizer_result, validate_optimizer_packing}",
        area: PortArea::Optimizer,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/plugins/optimizer/src/*",
        target: "optimizer::solve",
        area: PortArea::Optimizer,
        status: PortStatus::OracleTested,
    },
    PortDescriptor {
        upstream: "lib/optimizer/{dist,debug}/optimizer.{js,wasm}",
        target: "tools/bp-studio-oracle optimizer-solve",
        area: PortArea::Oracle,
        status: PortStatus::OracleTested,
    },
    PortDescriptor {
        upstream: "src/client/plugins/optimizer/src/{math/scale.*,sheet/*,branching/branchingContext.* coordinate conversions}",
        target: "optimizer::kernel",
        area: PortArea::Optimizer,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/plugins/optimizer/src/constraint/*",
        target: "optimizer::kernel constraint evaluators",
        area: PortArea::Optimizer,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/plugins/optimizer/src/class/{problem,hierarchy,parent,flap}.* and main.cpp read_initial_vector",
        target: "optimizer::kernel::{KernelProblem, KernelHierarchy, read_initial_vector}",
        area: PortArea::Optimizer,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/plugins/optimizer/src/branching/{branchingContext,greedy}.* helper logic",
        target: "optimizer::kernel::{BranchingContext, select_meg, annulus}",
        area: PortArea::Optimizer,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/plugins/optimizer/src/math/heuristics.cpp deterministic helpers",
        target: "optimizer::kernel::{make_circles, generate_in_circles, generate_random_vector, estimate_total}",
        area: PortArea::Optimizer,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/plugins/{cp,optimizer}/index.ts worker-facing contracts",
        target: "oristudio-bp-wasm::{bp_export_cp, bp_export_fold, bp_optimizer_request, bp_optimizer_template, bp_replace_with_optimizer_template, bp_optimizer_solve, bp_optimizer_solve_report, bp_validate_optimizer_packing}",
        area: PortArea::Wasm,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/fraction.ts",
        target: "math::rational",
        area: PortArea::Math,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/utils/gcd.ts",
        target: "math::gcd",
        area: PortArea::Math,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/invalidParameterError.ts",
        target: "math::rational, BpError::InvalidInput",
        area: PortArea::Math,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/shared/types/{constants,direction,geometry}.ts",
        target: "shared, math::geometry, sweep::rr_intersection",
        area: PortArea::Model,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/shared/types/*.d.ts and type-only helper aliases",
        target: "Rust static types",
        area: PortArea::Model,
        status: PortStatus::DocumentedDifference,
    },
    PortDescriptor {
        upstream: "src/shared/utils/{array,color,map,pattern,set}.ts",
        target: "shared",
        area: PortArea::Data,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/shared/utils/{clone,copy}.ts",
        target: "Rust Clone/serde ownership",
        area: PortArea::Data,
        status: PortStatus::DocumentedDifference,
    },
    PortDescriptor {
        upstream: "src/core/design/context/aabb/{aabb,aabbSide}.ts",
        target: "tree::Aabb",
        area: PortArea::Tree,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/context/{tree,treeNode,treeUtils}.ts",
        target: "tree::BpTree",
        area: PortArea::Tree,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/context/areaTree/{areaNode,areaTree,utils}.ts",
        target: "tree::AreaTree",
        area: PortArea::Optimizer,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/tasks/{height,balance,structure,aabb}.ts",
        target: "tree::BpTree::recompute",
        area: PortArea::Tree,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/service/{updateModel.d.ts,updateResult.ts}",
        target: "engine::update",
        area: PortArea::Engine,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/service/processor.ts",
        target: "engine::processor",
        area: PortArea::Engine,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/service/state.ts",
        target: "engine::state",
        area: PortArea::Engine,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/controller/treeController.ts",
        target: "engine::BpSession tree commands",
        area: PortArea::Engine,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/controller/designController.ts",
        target: "engine::BpSession design init/update",
        area: PortArea::Engine,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/client/project/changes/{commands/*,step.ts}",
        target: "engine::history",
        area: PortArea::Engine,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/project/changes/history.ts",
        target: "engine::history::HistoryManager",
        area: PortArea::Engine,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/client/project/components/grid/*",
        target: "grid",
        area: PortArea::Model,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/client/project/components/sheet.ts pure grid transforms",
        target: "grid",
        area: PortArea::Model,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/store.ts",
        target: "layout::Store",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/junction/validJunction.ts",
        target: "layout::ValidJunction",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/junction/{junction,invalidJunction}.ts",
        target: "layout::{create_junction, InvalidJunction}",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/tasks/invalidJunction.ts",
        target: "layout::InvalidJunction plus engine task TODO",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/nodeSet.ts",
        target: "layout::NodeSet",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/repository.ts",
        target: "layout::LayoutRepository::{init_with_tree, complete_with_tree, initialize_selected_pattern_with_tree}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/stretch.ts",
        target: "layout::LayoutStretch",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/tasks/stretch.ts",
        target: "layout::{create_valid_junctions, group_junctions, uncovered_junction_indices, LayoutStretch}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/quadrant.ts",
        target: "layout::Quadrant::{start_end_points, overlap_corner}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/region.ts",
        target: "layout::pattern::axis_parallels",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/piece.ts",
        target: "layout::pattern::PatternPiece",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/addOn.ts",
        target: "layout::pattern::PatternAddOn",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/gadget.ts",
        target: "layout::pattern::PatternGadget",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/device.ts",
        target: "layout::pattern::PatternDevice",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/pattern.ts",
        target: "layout::pattern::LayoutPattern",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/positioners/positioningContext.ts",
        target: "layout::pattern::LayoutPattern",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/positioners/singleJunctionPositioner.ts",
        target: "layout::pattern::LayoutPattern",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/positioners/twoJunctionPositioner.ts",
        target: "layout::pattern::LayoutPattern::new_positioned_with_repo",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/trace/hingeSegment.ts",
        target: "layout::trace::create_hinge_segments",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/trace/{trace,traceContext}.ts",
        target: "layout::trace::{Trace, get_next_intersection}",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/trace/repoTrace.ts",
        target: "layout::trace::RepoTrace::{from_repository, resolve_start_end}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/tasks/utils/expand.ts",
        target: "layout::contours::{expand_path, simplify}",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/tasks/roughContour.ts",
        target: "layout::contours::{build_rough_contours, leaf_rough_contour, expand_rough_contours}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/tasks/utils/combine.ts",
        target: "layout::contours::{combine_contours, combine_graphical_contours, to_graphical_contours_ex}",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/tasks/patternContour.ts",
        target: "layout::contours::{build_pattern_contours, create_start_end_map, process_pattern_contours}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/tasks/traceContour.ts",
        target: "layout::contours::{build_trace_contours, critical_corners_for_node, create_trace_contour, create_raw_contour}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/tasks/graphics.ts",
        target: "layout::graphics::{node_graphics, repo_device_graphics, flap_ridges, river_ridges, device_graphics}",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/generators/configGeneratorContext.ts",
        target: "layout::generators::ConfigGeneratorContext",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/generators/searchUtils/relay.ts",
        target: "layout::generators::search_relay",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/generators/searchUtils/splitJoin.ts",
        target: "layout::generators::{to_split_items, get_exposed_part}",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/generators/patternGenerator.ts",
        target: "layout::generators::{pattern_generator, pattern_generator_with_repo}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/generators/filters.ts",
        target: "layout::generators::{create_config_filter, create_config_filter_with_repo}",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/generators/singleConfigGenerator.ts",
        target: "layout::generators::single_config_generator",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/generators/configGenerator.ts",
        target: "layout::generators::{config_generator, config_generator_with_repo}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/generators/generalConfigGenerator.ts",
        target: "layout::generators::general_config_generator",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/generators/generalConfigGeneratorContext.ts",
        target: "layout::generators::GeneralConfigGeneratorContext",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/joiner/joiner.ts",
        target: "layout::joiner::Joiner",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/joiner/joinee.ts",
        target: "layout::joiner::Joinee",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/joiner/joineeBuilder.ts",
        target: "layout::joiner::JoineeBuilder",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/joiner/logic/joinLogic.ts",
        target: "layout::joiner::JoinLogic",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/joiner/logic/simpleJoinLogic.ts",
        target: "layout::joiner::simple_join_logic",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/joiner/logic/baseJoinLogic.ts",
        target: "layout::joiner::base_join_logic",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/joiner/logic/standardJoinLogic.ts",
        target: "layout::joiner::standard_join_logic",
        area: PortArea::Layout,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/generators/deviceGenerator.ts",
        target: "layout::generators::{device_generator, device_generator_with_repo}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/configuration.ts",
        target: "layout::LayoutConfiguration::{generate_patterns_with_repo, side_diagonals}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/partition.ts",
        target: "layout::LayoutPartition::{external_connection_targets, external_connection_target}",
        area: PortArea::Layout,
        status: PortStatus::Porting,
    },
    PortDescriptor {
        upstream: "src/core/design/context/index.d.ts",
        target: "Rust tree/model/static types",
        area: PortArea::Tree,
        status: PortStatus::DocumentedDifference,
    },
    PortDescriptor {
        upstream: "src/shared/data/heap/*",
        target: "data::heap",
        area: PortArea::Data,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/shared/data/doubleMap/*",
        target: "data::double_map",
        area: PortArea::Data,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/shared/data/diff/*",
        target: "data::diff",
        area: PortArea::Data,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/shared/data/unionFind/*",
        target: "data::union_find",
        area: PortArea::Data,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/shared/data/bst/ravlTree.ts",
        target: "data::bst::RavlTree",
        area: PortArea::Data,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/shared/data/bst/avlTree.ts",
        target: "data::bst::AvlTree",
        area: PortArea::Data,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/shared/data/bst/redBlackTree.ts",
        target: "data::bst::RedBlackTree",
        area: PortArea::Data,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/geometry/{float,couple,point,vector,matrix,line,rectangle}.ts",
        target: "math::geometry",
        area: PortArea::Math,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/geometry/{path,rationalPath,pointInPolygon,winding}.ts",
        target: "math::geometry",
        area: PortArea::Math,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/gops.ts",
        target: "math::gops",
        area: PortArea::Math,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/kamiya.ts",
        target: "math::kamiya",
        area: PortArea::Math,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/shared/types/cp.ts",
        target: "sweep::{CreaseType,CpLine}",
        area: PortArea::Sweep,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/sweepLine/stacking/stacking.ts",
        target: "sweep::stacking::{get_stacking, get_stacking_ex}",
        area: PortArea::Sweep,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/sweepLine/clip/clip.ts",
        target: "sweep::clip",
        area: PortArea::Sweep,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/sweepLine/clip/{overlap,overlapIntersector}.ts",
        target: "sweep::overlap",
        area: PortArea::Sweep,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/sweepLine/polyBool/aaUnion/{aaUnion,aaEventProvider,aaIntersector}.ts",
        target: "sweep::aa_union",
        area: PortArea::Sweep,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/sweepLine/classes/{chainer/chainer,segment/aaLineSegment}.ts",
        target: "sweep::aa_union",
        area: PortArea::Sweep,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/sweepLine/polyBool/generalUnion/{generalUnion,generalComparators,generalEventProvider,generalIntersector}.ts",
        target: "sweep::general_union",
        area: PortArea::Sweep,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/sweepLine/{classes/chainer/arcChainer,classes/segment/arcSegment,polyBool/rrIntersection/*}.ts",
        target: "sweep::rr_intersection",
        area: PortArea::Sweep,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/sweepLine/{classes/chainer/unionChainer,polyBool/aaUnion/roughUnion}.ts",
        target: "sweep::rough_union",
        area: PortArea::Sweep,
        status: PortStatus::UnitTested,
    },
    PortDescriptor {
        upstream: "src/core/math/sweepLine/{shared engine internals,polyBool scaffolding}/*",
        target: "sweep concrete operation modules",
        area: PortArea::Sweep,
        status: PortStatus::DocumentedDifference,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/positioners/singleJunctionPositioner.ts#todo-four-or-more-devices",
        target: "layout::position",
        area: PortArea::Layout,
        status: PortStatus::UpstreamGap,
    },
    PortDescriptor {
        upstream: "src/core/design/layout/pattern/positioners/twoJunctionPositioner.ts#todo-general-case",
        target: "layout::position",
        area: PortArea::Layout,
        status: PortStatus::UpstreamGap,
    },
];

pub fn port_descriptors() -> &'static [PortDescriptor] {
    PORT_DESCRIPTORS
}
