//! Cross-language golden for the four-point crease transform.
//!
//! The web surface previews a move/copy gesture by transforming the selected
//! creases in the browser (a kernel round trip per mouse move would re-transport
//! the whole selection). That mirror lives in
//! `apps/web/src/cp-workspace/tools/creaseTransform.ts` and must not drift from
//! `operations::transform::transform_segments_by_points`.
//!
//! This test writes the kernel's answer for a table of point quadruples into
//! `tests/fixtures/cp/crease-transform-golden.json`, which
//! `creaseTransform.test.ts` reads back. Changing the math on either side
//! fails on the other.
//!
//! Regenerate after an intentional change:
//!
//! ```sh
//! ORISTUDIO_UPDATE_GOLDEN=1 cargo test -p oristudio-cp --test transform_preview_golden
//! ```

use std::path::PathBuf;

use oristudio_cp::geometry::{LineColor, LineSegment, Point};
use oristudio_cp::operations::transform::transform_segments_by_points;
use serde_json::{Value, json};

/// Points the transform is applied to — an L, a diagonal, and off-origin spans.
fn probe_segments() -> Vec<LineSegment> {
    [
        (0.0, 0.0, 1.0, 0.0),
        (0.0, 0.0, 0.0, 1.0),
        (-2.5, 3.25, 4.75, -1.5),
        (100.0, 100.0, 100.5, 99.25),
    ]
    .iter()
    .map(|(ax, ay, bx, by)| {
        LineSegment::with_color(
            Point::new(*ax, *ay),
            Point::new(*bx, *by),
            LineColor::Black0,
        )
    })
    .collect()
}

/// One source pair → target pair the transform is resolved from.
struct TransformCase {
    source_a: [f64; 2],
    source_b: [f64; 2],
    target_a: [f64; 2],
    target_b: [f64; 2],
}

/// Identity, pure translation, right angles, a 180° flip, pure scale, and
/// arbitrary rotate+scale combinations off the origin.
fn cases() -> Vec<TransformCase> {
    [
        ([0.0, 0.0], [1.0, 0.0], [0.0, 0.0], [1.0, 0.0]),
        ([0.0, 0.0], [1.0, 0.0], [5.0, -3.0], [6.0, -3.0]),
        ([0.0, 0.0], [1.0, 0.0], [0.0, 0.0], [0.0, 1.0]),
        ([0.0, 0.0], [1.0, 0.0], [0.0, 0.0], [0.0, -1.0]),
        ([0.0, 0.0], [1.0, 0.0], [0.0, 0.0], [-1.0, 0.0]),
        ([0.0, 0.0], [1.0, 0.0], [0.0, 0.0], [3.0, 0.0]),
        ([0.0, 0.0], [1.0, 0.0], [2.0, 2.0], [4.5, 5.75]),
        ([1.0, 1.0], [3.0, 2.0], [-4.0, 0.5], [-1.25, 6.0]),
        ([-2.0, -2.0], [-2.0, 5.0], [10.0, 1.0], [3.5, 1.0]),
        ([0.25, 0.75], [0.5, 0.5], [0.0, 0.0], [1.0, 1.0]),
    ]
    .into_iter()
    .map(|(source_a, source_b, target_a, target_b)| TransformCase {
        source_a,
        source_b,
        target_a,
        target_b,
    })
    .collect()
}

fn golden_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures/cp/crease-transform-golden.json")
}

fn build_golden() -> Value {
    let segments = probe_segments();
    let entries: Vec<Value> = cases()
        .into_iter()
        .map(|case| {
            let mut transformed = segments.clone();
            transform_segments_by_points(
                &mut transformed,
                Point::new(case.source_a[0], case.source_a[1]),
                Point::new(case.source_b[0], case.source_b[1]),
                Point::new(case.target_a[0], case.target_a[1]),
                Point::new(case.target_b[0], case.target_b[1]),
            );
            json!({
                "sourceA": case.source_a,
                "sourceB": case.source_b,
                "targetA": case.target_a,
                "targetB": case.target_b,
                "transformed": transformed
                    .iter()
                    .map(|s| json!([s.a.x, s.a.y, s.b.x, s.b.y]))
                    .collect::<Vec<_>>(),
            })
        })
        .collect();

    json!({
        "comment": "Generated by crates/oristudio-cp/tests/transform_preview_golden.rs. \
                    Regenerate with ORISTUDIO_UPDATE_GOLDEN=1.",
        "segments": probe_segments()
            .iter()
            .map(|s| json!([s.a.x, s.a.y, s.b.x, s.b.y]))
            .collect::<Vec<_>>(),
        "cases": entries,
    })
}

#[test]
fn four_point_transform_matches_the_committed_golden() {
    let golden = build_golden();
    let path = golden_path();
    let serialized = format!("{}\n", serde_json::to_string_pretty(&golden).unwrap());

    if std::env::var_os("ORISTUDIO_UPDATE_GOLDEN").is_some() {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("create fixture directory");
        }
        std::fs::write(&path, &serialized).expect("write golden fixture");
        return;
    }

    let committed = std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "missing golden fixture {}: {error}. Regenerate with ORISTUDIO_UPDATE_GOLDEN=1.",
            path.display()
        )
    });
    let committed: Value = serde_json::from_str(&committed).expect("parse golden fixture");

    // Numbers are compared with a tolerance rather than for bit equality:
    // serde_json's default float parser is not round-trip exact (that needs its
    // `float_roundtrip` feature), so reading back a value this test itself wrote can
    // land a ulp away. The fixture text is exact — JS `JSON.parse` reads it exactly,
    // which is what the web-side golden test relies on — so the slack here is purely
    // Rust's read-back, well below anything the preview could show.
    assert_json_close(&committed, &golden, "$");
}

/// Structural equality with a relative tolerance on numbers.
fn assert_json_close(left: &Value, right: &Value, path: &str) {
    match (left, right) {
        (Value::Number(l), Value::Number(r)) => {
            let (l, r) = (l.as_f64().unwrap(), r.as_f64().unwrap());
            let tolerance = 1e-12 * (1.0 + l.abs().max(r.abs()));
            assert!(
                (l - r).abs() <= tolerance,
                "four-point transform drifted from the committed golden at {path}: \
                 {l} vs {r}. If intentional, regenerate with ORISTUDIO_UPDATE_GOLDEN=1 \
                 and re-run the web creaseTransform golden test."
            );
        }
        (Value::Array(l), Value::Array(r)) => {
            assert_eq!(l.len(), r.len(), "golden array length differs at {path}");
            for (index, (l, r)) in l.iter().zip(r).enumerate() {
                assert_json_close(l, r, &format!("{path}[{index}]"));
            }
        }
        (Value::Object(l), Value::Object(r)) => {
            // Key *sets*, not key order: whether a parsed map preserves file order or
            // sorts depends on serde_json's `preserve_order` feature, which a workspace
            // build turns on through feature unification and a single-crate build does
            // not. Comparing order made this test pass under `-p oristudio-cp` and fail
            // under `--workspace`.
            let mut left_keys = l.keys().collect::<Vec<_>>();
            let mut right_keys = r.keys().collect::<Vec<_>>();
            left_keys.sort();
            right_keys.sort();
            assert_eq!(left_keys, right_keys, "golden object keys differ at {path}");
            for (key, l) in l {
                assert_json_close(l, &r[key], &format!("{path}.{key}"));
            }
        }
        (l, r) => assert_eq!(l, r, "golden differs at {path}"),
    }
}
