//! Cross-language golden for "which crease endpoints sit on this vertex".
//!
//! The Move Vertex tool previews its drag in the browser — the real strokes
//! follow the cursor, with the touched endpoints moved through the transform
//! channel — so the *preview* decides the match set in TypeScript while the
//! *commit* decides it again in Rust. A one-crease disagreement between them
//! shows four creases following the cursor and commits three, leaving the fourth
//! stretched to nowhere.
//!
//! The mirror lives in `apps/web/src/cp-workspace/tools/vertexEndpoints.ts` and
//! must not drift from `operations::native::vertex::vertex_endpoints_at`. This
//! test writes the kernel's answer for a table of probe points into
//! `tests/fixtures/cp/vertex-move-match-golden.json`, which
//! `vertexEndpoints.test.ts` reads back. Changing the rule on either side fails
//! on the other.
//!
//! Regenerate after an intentional change:
//!
//! ```sh
//! ORISTUDIO_UPDATE_GOLDEN=1 cargo test -p oristudio-cp --test vertex_move_match_golden
//! ```

use std::path::PathBuf;

use oristudio_cp::geometry::{LineColor, LineSegment, Point};
use oristudio_cp::model::CreasePatternModel;
use oristudio_cp::operations::native::vertex::{
    EndpointSlot, VERTEX_COINCIDENCE, vertex_endpoints_at,
};
use serde_json::{Value, json};

/// The probe pattern, chosen to exercise every awkward case the rule has:
///
/// - a plain degree-4 junction at (100, 100)
/// - a crease whose endpoint is *just inside* the tolerance of that junction
/// - a crease whose endpoint is *just outside* it
/// - two endpoints that differ below the tolerance but whose `Math.round(v * 1e9)`
///   keys straddle a boundary, which is why the rule is an ε-ball and not a
///   quantization
/// - an already-degenerate zero-length crease, which matches on both ends
fn probe_segments() -> Vec<LineSegment> {
    let inside = VERTEX_COINCIDENCE * 0.5;
    let outside = VERTEX_COINCIDENCE * 2.0;
    // Two values a hair apart that `Math.round(v * 1e9)` puts in different
    // buckets: 0.0000000005 rounds to 1 and 0.0000000004999 rounds to 0.
    let straddle_low = 4.999e-10;
    let straddle_high = 5.0e-10;

    [
        (100.0, 100.0, 0.0, 100.0),
        (100.0, 100.0, 200.0, 100.0),
        (100.0, 100.0, 100.0, 0.0),
        (100.0, 100.0, 100.0, 200.0),
        (100.0 + inside, 100.0, 180.0, 20.0),
        (100.0 + outside, 100.0, 180.0, 180.0),
        (straddle_low, straddle_low, 50.0, 0.0),
        (straddle_high, straddle_high, 0.0, 50.0),
        (300.0, 300.0, 300.0, 300.0),
        // Far from every probe, so it must never match.
        (-50.0, -50.0, -50.0, 50.0),
    ]
    .iter()
    .map(|(ax, ay, bx, by)| {
        LineSegment::with_color(Point::new(*ax, *ay), Point::new(*bx, *by), LineColor::Red1)
    })
    .collect()
}

/// Points the match rule is asked about: the junction itself, offsets either
/// side of the tolerance, the rounding-boundary origin, the degenerate crease,
/// and a place with nothing on it.
fn probe_points() -> Vec<[f64; 2]> {
    let inside = VERTEX_COINCIDENCE * 0.5;
    let outside = VERTEX_COINCIDENCE * 2.0;
    vec![
        [100.0, 100.0],
        [100.0 + inside, 100.0],
        [100.0 + outside, 100.0],
        [100.0, 100.0 + VERTEX_COINCIDENCE],
        [0.0, 0.0],
        [300.0, 300.0],
        [55.0, 55.0],
        [0.0, 100.0],
    ]
}

fn model() -> CreasePatternModel {
    CreasePatternModel {
        line_segments: probe_segments(),
        ..CreasePatternModel::default()
    }
}

fn golden_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures/cp/vertex-move-match-golden.json")
}

fn build_golden() -> Value {
    let model = model();
    let cases: Vec<Value> = probe_points()
        .into_iter()
        .map(|probe| {
            let matched = vertex_endpoints_at(&model, Point::new(probe[0], probe[1]));
            json!({
                "point": probe,
                "matched": matched
                    .iter()
                    .map(|endpoint| json!({
                        "segment": endpoint.segment,
                        "slot": match endpoint.slot {
                            EndpointSlot::A => "a",
                            EndpointSlot::B => "b",
                        },
                    }))
                    .collect::<Vec<_>>(),
            })
        })
        .collect();

    json!({
        "comment": "Generated by crates/oristudio-cp/tests/vertex_move_match_golden.rs. \
                    Regenerate with ORISTUDIO_UPDATE_GOLDEN=1.",
        "tolerance": VERTEX_COINCIDENCE,
        "segments": probe_segments()
            .iter()
            .map(|s| json!([s.a.x, s.a.y, s.b.x, s.b.y]))
            .collect::<Vec<_>>(),
        "cases": cases,
    })
}

#[test]
fn vertex_match_rule_matches_the_committed_golden() {
    let golden = build_golden();
    let path = golden_path();
    let serialized = format!("{}\n", serde_json::to_string_pretty(&golden).unwrap());

    if std::env::var_os("ORISTUDIO_UPDATE_GOLDEN").is_some() {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("create fixture directory");
        }
        std::fs::write(&path, &serialized).expect("write golden fixture");
        return;
    }

    let committed = std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "missing golden fixture {}: {error}. Regenerate with ORISTUDIO_UPDATE_GOLDEN=1.",
            path.display()
        )
    });
    let committed: Value = serde_json::from_str(&committed).expect("parse golden fixture");

    // Same tolerance rationale as `transform_preview_golden`: serde_json's default
    // float parser is not round-trip exact, so a value this test wrote can read
    // back a ulp away. The *matched sets* are compared exactly — they are integers
    // and strings, and they are the thing that must not drift.
    assert_json_close(&committed, &golden, "$");
}

/// Structural equality with a relative tolerance on numbers.
fn assert_json_close(left: &Value, right: &Value, path: &str) {
    match (left, right) {
        (Value::Number(l), Value::Number(r)) => {
            let (l, r) = (l.as_f64().unwrap(), r.as_f64().unwrap());
            let tolerance = 1e-12 * (1.0 + l.abs().max(r.abs()));
            assert!(
                (l - r).abs() <= tolerance,
                "vertex match golden drifted at {path}: {l} vs {r}. If intentional, \
                 regenerate with ORISTUDIO_UPDATE_GOLDEN=1 and re-run the web \
                 vertexEndpoints golden test."
            );
        }
        (Value::Array(l), Value::Array(r)) => {
            assert_eq!(l.len(), r.len(), "golden array length differs at {path}");
            for (index, (l, r)) in l.iter().zip(r).enumerate() {
                assert_json_close(l, r, &format!("{path}[{index}]"));
            }
        }
        (Value::Object(l), Value::Object(r)) => {
            // Key sets, not key order — see `transform_preview_golden` for why a
            // workspace build and a single-crate build disagree about order.
            let mut left_keys = l.keys().collect::<Vec<_>>();
            let mut right_keys = r.keys().collect::<Vec<_>>();
            left_keys.sort();
            right_keys.sort();
            assert_eq!(left_keys, right_keys, "golden object keys differ at {path}");
            for (key, l) in l {
                assert_json_close(l, &r[key], &format!("{path}.{key}"));
            }
        }
        (l, r) => assert_eq!(l, r, "golden differs at {path}"),
    }
}
