import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import { decodeCompactGeometryBytes } from './oristudioCpNativeClient';

// The cross-language pin for the compact-geometry wire format.
//
// These bytes are not written here — they are read from a fixture the Rust
// encoder produces (`binary_codec_golden_fixture_is_current` in
// crates/oristudio-cp/src/geometry_transport.rs), so there is no copy of them
// to fall out of date. Change the format and that Rust test fails until the
// fixture is regenerated; the regenerated bytes then arrive here, and this test
// fails until the decoder below understands them.
//
// It used to be an inline array, and it went stale: the format moved OCG1 ->
// OCG2 and this file stayed on OCG1, so the suite passed while every payload
// from the native engine failed its magic check and the desktop editor opened
// nothing at all.
//
// Resolved from the vitest root (apps/web) rather than from this file: Vite
// rewrites `import.meta.url` during transform, so it is not a filesystem path.
const GOLDEN_FIXTURE = resolve(
  process.cwd(),
  '../../tests/fixtures/oristudio-cp/compact-geometry-golden.bin',
);

function readGoldenFixture(): Uint8Array {
  try {
    return new Uint8Array(readFileSync(GOLDEN_FIXTURE));
  } catch (error) {
    throw new Error(
      `compact-geometry golden fixture not found at ${GOLDEN_FIXTURE}. ` +
        'It is generated by the Rust encoder: ' +
        'UPDATE_FIXTURES=1 cargo test -p oristudio-cp --lib binary_codec_golden',
      { cause: error },
    );
  }
}

const GOLDEN_BYTES = readGoldenFixture();

function bufferOf(bytes: Uint8Array): ArrayBuffer {
  // A standalone ArrayBuffer copy (offset 0), matching what invoke returns.
  return bytes.slice().buffer;
}

describe('decodeCompactGeometryBytes', () => {
  // Fails first, and most legibly, when the encoder moves on.
  it('is a current-version buffer, not a stale one', () => {
    const magic = new DataView(bufferOf(GOLDEN_BYTES)).getUint32(0, true);
    expect(String.fromCharCode(...GOLDEN_BYTES.slice(0, 4))).toBe('2GCO'); // "OCG2", little-endian
    expect(magic).toBe(0x4f_43_47_32);
  });

  it('decodes the real Rust-encoded golden buffer', () => {
    const geometry = decodeCompactGeometryBytes(bufferOf(GOLDEN_BYTES));
    expect(Array.from(geometry.segEndpoints)).toEqual([1, 2, 3, 4]);
    expect(Array.from(geometry.segAttr)).toEqual([5, 6, 7, 8]);
    expect(Array.from(geometry.segCustomColor)).toEqual([9, 10, 11]);
    // Empty means "every segment is classic" — the common case, and what the
    // encoder writes when no segment carries a magnitude.
    expect(Array.from(geometry.segFoldMagnitude ?? [])).toEqual([]);
    expect(Array.from(geometry.auxEndpoints)).toEqual([]);
    expect(Array.from(geometry.pointCoords)).toEqual([12, 13]);
    expect(Array.from(geometry.circleData)).toEqual([]);
    // Tail round-trips through JSON (grid/operationFrame present by default).
    expect(geometry.tail).toBeTruthy();
    // Views are real typed arrays.
    expect(geometry.segEndpoints).toBeInstanceOf(Float64Array);
    expect(geometry.segAttr).toBeInstanceOf(Int32Array);
    expect(geometry.segCustomColor).toBeInstanceOf(Uint8Array);
  });

  it('throws on a bad magic', () => {
    const bytes = GOLDEN_BYTES.slice();
    bytes[0] ^= 0xff;
    expect(() => decodeCompactGeometryBytes(bufferOf(bytes))).toThrow();
  });

  // The exact shape of the bug this file failed to catch: a previous-version
  // buffer must be refused outright rather than misparsed.
  it('refuses a previous-version (OCG1) buffer', () => {
    const bytes = GOLDEN_BYTES.slice();
    bytes[0] = '1'.charCodeAt(0); // OCG2 -> OCG1
    expect(() => decodeCompactGeometryBytes(bufferOf(bytes))).toThrow(
      expect.objectContaining({ code: 'geometry_decode' }),
    );
  });

  it('throws on a truncated buffer (length disagrees with header)', () => {
    const bytes = GOLDEN_BYTES.slice(0, GOLDEN_BYTES.length - 1);
    expect(() => decodeCompactGeometryBytes(bufferOf(bytes))).toThrow();
  });

  it('throws on a buffer too small for the header', () => {
    expect(() => decodeCompactGeometryBytes(new ArrayBuffer(4))).toThrow();
  });
});
