/**
 * The similarity transform behind the crease move/copy tools, mirrored from the
 * kernel so the live preview shows exactly what the commit will produce.
 *
 * The kernel arm is `operations::transform::transform_segments_by_points`
 * (Oriedita's `FoldLineSet.move(ta, tb, tc, td)`): rotate about the first source
 * point by the angle from the source pair to the target pair, scale by the ratio
 * of their lengths, then translate source-first-point → target-first-point.
 *
 * This is a *preview-only* mirror — the mutation still runs kernel-side — but the
 * two must not drift, so `creaseTransform.golden.test.ts` checks this module
 * against points produced by the Rust implementation
 * (`tests/fixtures/cp/crease-transform-golden.json`, regenerated by
 * `crates/oristudio-cp/tests/transform_preview_golden.rs`).
 */
import type { CpAffineMatrix } from '../adapters/cpSnapshotToScene';
import type { ModelPoint } from '../renderer/types';

/** The kernel's sentinel for "no direction" (a zero-length pair). */
const NO_ANGLE = -10000;

/**
 * Direction of `a → b` in degrees, normalised to [0, 360).
 *
 * Mirrors `AngleInput for (Point, Point)` in `geometry::orita_calc`, including its
 * quirks: the cosine is clamped at +1 only (never at -1), and a zero-length pair
 * returns the {@link NO_ANGLE} sentinel rather than throwing.
 */
export function segmentAngleDeg(a: ModelPoint, b: ModelPoint): number {
  const x = b.x - a.x;
  const y = b.y - a.y;
  const length = Math.sqrt(x * x + y * y);
  if (length <= 0) return NO_ANGLE;

  let c = x / length;
  if (c > 1) c = 1;

  let ret = Math.acos(c);
  if (y < 0) ret = -ret;
  ret = (180 * ret) / Math.PI;
  if (ret < 0) ret += 360;
  return ret;
}

/** Mirrors `geometry::orita_calc::angle_between_0_360`. */
export function angleBetween0360(value: number): number {
  let v = value;
  while (v < 0) v += 360;
  while (v >= 360) v -= 360;
  return v;
}

/** The kernel's transform parameters: rotate about `pivot`, scale, then translate. */
export interface CpSimilarity {
  /** Rotation in degrees, in [0, 360). */
  rotationDeg: number;
  scale: number;
  /** Rotation centre — the first source point. */
  pivot: ModelPoint;
  /** Post-rotation translation, first source point → first target point. */
  delta: ModelPoint;
}

/**
 * Resolve the similarity taking the source pair onto the target pair.
 *
 * Returns `null` for a degenerate pair, which the surface reads as "show the placed
 * dots, no ghost":
 *
 * - A coincident *source* pair would divide by `|o1 o2| = 0` for the scale, giving
 *   Infinity/NaN geometry. Oriedita never reaches that state — its
 *   `release_select_2_original_points` rejects a second source point within the
 *   selection distance of the first — but our tool has no such rejection.
 * - A coincident *target* pair is a live hover state (the cursor passing over the
 *   third point), where the kernel's scale of 0 would collapse the whole selection
 *   onto a single point. Blanking the ghost for that instant reads better than
 *   flashing a dot, and the gesture is not committed until a click.
 */
export function similarityFromPointPairs(
  sourceA: ModelPoint,
  sourceB: ModelPoint,
  targetA: ModelPoint,
  targetB: ModelPoint
): CpSimilarity | null {
  const sourceLength = Math.hypot(sourceB.x - sourceA.x, sourceB.y - sourceA.y);
  if (!(sourceLength > 0)) return null;

  const sourceAngle = segmentAngleDeg(sourceA, sourceB);
  const targetAngle = segmentAngleDeg(targetA, targetB);
  if (sourceAngle === NO_ANGLE || targetAngle === NO_ANGLE) return null;

  return {
    rotationDeg: angleBetween0360(targetAngle - sourceAngle),
    scale: Math.hypot(targetB.x - targetA.x, targetB.y - targetA.y) / sourceLength,
    pivot: sourceA,
    delta: { x: targetA.x - sourceA.x, y: targetA.y - sourceA.y },
  };
}

/**
 * Fold a {@link CpSimilarity} into the affine the scene adapters consume.
 *
 * The kernel evaluates `r * (cos * (x - ax) - sin * (y - ay)) + ax + dx` per point;
 * the matrix form re-associates that arithmetic, so results can differ in the last
 * ulp. That is preview-only slack — the committed geometry comes from the kernel —
 * and the golden test pins the two to well inside a pixel.
 */
export function matrixFromSimilarity(similarity: CpSimilarity): CpAffineMatrix {
  const { rotationDeg, scale, pivot, delta } = similarity;
  const radians = (rotationDeg * Math.PI) / 180;
  const cos = Math.cos(radians) * scale;
  const sin = Math.sin(radians) * scale;
  return [
    cos,
    -sin,
    sin,
    cos,
    -cos * pivot.x + sin * pivot.y + pivot.x + delta.x,
    -sin * pivot.x - cos * pivot.y + pivot.y + delta.y,
  ];
}

/** Convenience: the four-point transform as a matrix, or `null` if degenerate. */
export function matrixFromPointPairs(
  sourceA: ModelPoint,
  sourceB: ModelPoint,
  targetA: ModelPoint,
  targetB: ModelPoint
): CpAffineMatrix | null {
  const similarity = similarityFromPointPairs(sourceA, sourceB, targetA, targetB);
  return similarity === null ? null : matrixFromSimilarity(similarity);
}
