/**
 * Which crease endpoints sit on a vertex — the browser mirror of the kernel's
 * `operations::native::vertex::vertex_endpoints_at`.
 *
 * The Move Vertex tool previews its drag on the canvas (the real strokes follow
 * the cursor, with the touched endpoints moved through the transform channel),
 * so the *preview* decides this set here while the *commit* decides it again in
 * Rust. A one-crease disagreement would show four creases following the cursor
 * and commit three, leaving the fourth stretched to nowhere — so the two are
 * pinned against each other by `vertexEndpoints.test.ts`, which reads a fixture
 * generated by `crates/oristudio-cp/tests/vertex_move_match_golden.rs`.
 *
 * Pure and free of the document shape: callers pass endpoint coordinates, so this
 * works off either the structured snapshot or the compact transport's typed
 * arrays.
 */
import type { ModelPoint } from '../renderer/types';

/**
 * How close an endpoint must be to count as sitting *on* a vertex. Must equal
 * `VERTEX_COINCIDENCE` in `crates/oristudio-cp/src/operations/native/vertex.rs`;
 * the golden test fails if it does not.
 *
 * Written as the same *product* the kernel evaluates (`Epsilon::FACTOR * 1E-5`)
 * rather than as the decimal it comes to. `0.01 * 1e-5` is not exactly `1e-7` in
 * binary floating point — it is one ulp above — so a transcribed literal is a
 * real, if microscopic, disagreement about where the tolerance ends. Doing the
 * same arithmetic is what makes the two sides equal rather than nearly equal.
 *
 * An ε-ball rather than a quantization on purpose: two coordinates a picometre
 * apart can straddle a rounding boundary, which would make "is this the same
 * vertex" depend on where the pattern happens to sit on the paper.
 */
export const VERTEX_COINCIDENCE = 0.01 * 1e-5;

/** Which end of a segment a match landed on. */
export type VertexEndpointSlot = 'a' | 'b';

export interface VertexEndpointMatch {
  /** Zero-based index into the segment list — one *less* than the line id. */
  segment: number;
  slot: VertexEndpointSlot;
}

/** The endpoint coordinates this module reads. */
export interface VertexEndpointSegment {
  a: ModelPoint;
  b: ModelPoint;
}

function within(px: number, py: number, vertex: ModelPoint): boolean {
  return Math.hypot(px - vertex.x, py - vertex.y) <= VERTEX_COINCIDENCE;
}

/**
 * Every crease endpoint within {@link VERTEX_COINCIDENCE} of `vertex`, in segment
 * order, `a` before `b`.
 *
 * A segment with *both* endpoints on the vertex contributes two entries. That is
 * already-degenerate geometry, and the kernel reports it the same way, so the
 * mirror must too.
 */
export function vertexEndpointsAt(
  segments: readonly VertexEndpointSegment[],
  vertex: ModelPoint
): VertexEndpointMatch[] {
  const found: VertexEndpointMatch[] = [];
  for (let index = 0; index < segments.length; index++) {
    const segment = segments[index];
    if (within(segment.a.x, segment.a.y, vertex)) found.push({ segment: index, slot: 'a' });
    if (within(segment.b.x, segment.b.y, vertex)) found.push({ segment: index, slot: 'b' });
  }
  return found;
}

/**
 * The key {@link import('../adapters/cpSnapshotToScene').CpTransformPreview}'s
 * `endpoints` set is built from: `segmentIndex * 2 + (0 for a, 1 for b)`.
 *
 * A single number rather than a `${id}:${slot}` string because this is read twice
 * per segment per frame by both stroke builders, on the app's hottest surface.
 */
export function endpointKey(segment: number, slot: VertexEndpointSlot): number {
  return segment * 2 + (slot === 'a' ? 0 : 1);
}

/** The endpoint keys for a whole match list, ready for the preview channel. */
export function endpointKeys(matches: readonly VertexEndpointMatch[]): Set<number> {
  const keys = new Set<number>();
  for (const match of matches) keys.add(endpointKey(match.segment, match.slot));
  return keys;
}
