/**
 * One-time Sentry initialization.
 *
 * The client is passed in (dependency-injected) rather than imported here, so
 * tests can drive `initializeSentry` with a fake and assert the exact config.
 * Real wiring lives in `main.tsx`, which passes the `@sentry/react` namespace.
 *
 * This layer reports errors and nothing else: no tracing, no profiling, no
 * session replay. That is the same line the analytics layer draws with
 * `disable_session_recording: true`, and it keeps a crash report to the one
 * thing we asked Sentry for.
 */

import { getOrCreateStableId } from '../analytics/stableId';
import { appBuildInfo } from '../lib/appBuildInfo';
import { getRuntimeSurface } from '../platform/runtime';
import { isMonitoringConsented, setMonitoringEnabled } from './runtime';
import { scrubBreadcrumb, scrubEvent } from './scrub';
import type { SentryClientLike, SentryEnvironment } from './types';

export interface MonitoringBootstrapOptions {
  /** The user's current consent, decided before init runs. */
  monitoringEnabled: boolean;
}

/**
 * Noise that is never actionable, dropped before it costs quota.
 *
 * Deliberately short. Network failures are *not* here: this app fetches share
 * records and a large detector model, and a failure in either is a real bug we
 * would want to see. Add to this list from observed traffic, not from
 * speculation.
 */
const IGNORED_ERRORS: Array<string | RegExp> = [
  // Fires from any ResizeObserver-driven layout; benign and unfixable.
  /ResizeObserver loop/,
  // Thrown by injected scripts that rejected a non-Error value.
  /^Non-Error promise rejection captured/,
];

/** Injected extension scripts are not our bundle and not our bug. */
const DENY_URLS: Array<string | RegExp> = [
  /^chrome-extension:\/\//,
  /^moz-extension:\/\//,
  /^safari-web-extension:\/\//,
];

/**
 * Session pings are sent outside the event pipeline, so `beforeSend` never sees
 * them and could not stop them. Leaving the integration on would mean an
 * opted-out user still produced traffic to Sentry on every page load, which is
 * exactly what the toggle promises not to do. Release health is not worth that.
 */
const BROWSER_SESSION_INTEGRATION = 'BrowserSession';

/**
 * The release this build reports, and the key Sentry symbolication joins on:
 * an event is un-minified only if its release matches the one the sourcemaps
 * were uploaded under. `vite.config.ts` computes the string and stamps it into
 * both sides, so there is nothing here to keep in sync.
 *
 * The global only exists after Vite's define pass — Vitest runs the source
 * without it — so guard with `typeof`, the same way `appCommit()` does. The
 * fallback is only ever seen by tests, which assert the shape, not the value.
 */
function releaseName(): string {
  if (typeof __SENTRY_RELEASE__ === 'string' && __SENTRY_RELEASE__ !== '') {
    return __SENTRY_RELEASE__;
  }
  const build = appBuildInfo();
  return `ori-studio@${build.version}+${build.commit}`;
}

/**
 * Initialize Sentry if — and only if — the DSN is present at build time.
 *
 * Absence is the dev/prod firewall, the same one the analytics layer uses: local
 * and preview builds don't set the var, so `init` never runs and nothing is ever
 * sent. Returns whether Sentry was actually initialized, so callers know if a
 * live client exists.
 *
 * Note the DSN alone does not mean events flow. Consent is enforced separately,
 * in `beforeSend`, so the settings toggle takes effect immediately rather than
 * at the next reload. While opted out the SDK collects in memory and transmits
 * nothing.
 */
export function initializeSentry(
  client: SentryClientLike,
  options: MonitoringBootstrapOptions,
  env: SentryEnvironment
): boolean {
  const dsn = env.VITE_PUBLIC_SENTRY_DSN;

  if (!dsn) {
    if (env.DEV) {
      console.info('[monitoring] Sentry disabled: VITE_PUBLIC_SENTRY_DSN not set');
    }
    return false;
  }

  const build = appBuildInfo();

  // Seed consent before init, so the gate is already correct if the very first
  // event fires during initialization.
  setMonitoringEnabled(options.monitoringEnabled);

  client.init({
    dsn,
    environment: env.VITE_PUBLIC_SENTRY_ENVIRONMENT ?? 'production',
    // Matches the "0.1.2 (build a1b2c3d)" identity the error fallback shows, so
    // a copied report and a Sentry issue name the same build.
    release: releaseName(),
    tracesSampleRate: 0,
    sendDefaultPii: false,
    // Client reports are aggregate counts of dropped events. Harmless in
    // content, but they are still traffic generated by an opted-out user.
    sendClientReports: false,
    integrations: (defaults: Array<{ name: string }>) =>
      defaults.filter((integration) => integration.name !== BROWSER_SESSION_INTEGRATION),
    beforeSend: (event: Parameters<typeof scrubEvent>[0]) =>
      isMonitoringConsented() ? scrubEvent(event) : null,
    beforeBreadcrumb: (breadcrumb: Parameters<typeof scrubBreadcrumb>[0]) =>
      scrubBreadcrumb(breadcrumb),
    ignoreErrors: IGNORED_ERRORS,
    denyUrls: DENY_URLS,
    initialScope: {
      tags: {
        runtime_surface: getRuntimeSurface(),
        app_version: build.version,
        app_commit: build.commit,
      },
      // The anonymous id PostHog identifies with, so a crash can be joined to
      // the session that produced it.
      //
      // It has to be set *here* rather than only in `setMonitoringEnabled`.
      // That function needs a live client, and the client is bound later, by
      // `MonitoringRuntimeProvider`'s layout effect — so between `init` and
      // first render there is no user on the scope at all. That window is the
      // whole of startup: PostHog init, router construction, i18n, and the
      // first render of the tree. A crash there is exactly the kind you most
      // want to correlate, and it was arriving with no way to join on.
      //
      // Gated on consent because `getOrCreateStableId` *creates and persists*
      // an id as a side effect: calling it while opted out would mint an
      // identifier for someone who asked us not to.
      user: options.monitoringEnabled ? { id: getOrCreateStableId() } : undefined,
    },
  });

  return true;
}
