export const ORISTUDIO_BP_COMMAND_GROUPS = [
  { id: 'file', label: 'Files and workspaces', order: 10 },
  { id: 'view', label: 'Views and layers', order: 20 },
  { id: 'tree', label: 'Tree authoring', order: 30 },
  { id: 'layout', label: 'Packing layout', order: 40 },
  { id: 'stretch', label: 'Stretch, pattern, and device', order: 50 },
  { id: 'optimizer', label: 'Optimizer', order: 60 },
  { id: 'diagnostics', label: 'Diagnostics', order: 70 },
  { id: 'workspace', label: 'BPZ workspace', order: 80 },
] as const;

export type OristudioBpCommandGroupId = (typeof ORISTUDIO_BP_COMMAND_GROUPS)[number]['id'];

export type OristudioBpCommandPlacement =
  | 'menu'
  | 'toolbar'
  | 'tree-context'
  | 'packing-context'
  | 'inspector'
  | 'diagnostics'
  | 'hidden-ui-only';

export type OristudioBpCommandStatus =
  | 'planned'
  | 'porting'
  | 'ready'
  | 'unsupported'
  | 'upstream-gap'
  | 'ori-equivalent'
  | 'out-of-scope-ui';

export interface OristudioBpCommandDefinition {
  id: `bp.${string}`;
  capability: `bp.${string}`;
  label: string;
  group: OristudioBpCommandGroupId;
  placement: OristudioBpCommandPlacement;
  upstream: string;
  status: OristudioBpCommandStatus;
  disabledReason: string;
  tooltip: string;
  phase: number;
  selectionRequirement?: string;
  shortcut?: string;
}

export const ORISTUDIO_BP_COMMANDS = [
  {
    id: 'bp.file.newProject',
    capability: 'bp.file.newProject',
    label: 'New Box Pleat Project',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/services/workspaceService.ts:newProject',
    status: 'ready',
    disabledReason: 'Box pleat project creation is not wired yet',
    tooltip: 'Create a new Box Pleating Studio project',
    phase: 2,
  },
  {
    id: 'bp.file.openBps',
    capability: 'bp.file.openBps',
    label: 'Open BPS...',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/services/importService.ts',
    status: 'ready',
    disabledReason: 'BPS open is not wired yet',
    tooltip: 'Open a Box Pleating Studio project',
    phase: 2,
  },
  {
    id: 'bp.file.openBpz',
    capability: 'bp.file.openBpz',
    label: 'Open BPZ...',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/services/importService.ts',
    status: 'ready',
    disabledReason: 'BPZ open is not wired yet',
    tooltip: 'Open a Box Pleating Studio workspace archive',
    phase: 2,
  },
  {
    id: 'bp.file.importTreeMaker',
    capability: 'bp.file.importTreeMaker',
    label: 'Import TreeMaker File...',
    group: 'file',
    placement: 'menu',
    upstream: 'src/client/plugins/treeMaker/index.ts',
    status: 'ready',
    disabledReason: 'TreeMaker import into BP projects is not wired yet',
    tooltip: 'Import a TreeMaker v5 file through the BP Studio importer',
    phase: 2,
  },
  {
    id: 'bp.file.saveBps',
    capability: 'bp.file.saveBps',
    label: 'Save BPS',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/services/exportService.ts',
    status: 'ready',
    disabledReason: 'BPS save is not wired yet',
    tooltip: 'Save the active box pleat project',
    phase: 2,
    shortcut: 'Primary+S',
  },
  {
    id: 'bp.file.saveBpsAs',
    capability: 'bp.file.saveBpsAs',
    label: 'Save BPS As...',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/vue/gadgets/file/saveAs.vue',
    status: 'ready',
    disabledReason: 'BPS Save As is not wired yet',
    tooltip: 'Save the active box pleat project to a new file',
    phase: 2,
    shortcut: 'Primary+Shift+S',
  },
  {
    id: 'bp.file.saveBpz',
    capability: 'bp.file.saveBpz',
    label: 'Save BPZ Workspace',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/vue/modals/export/bpz.vue',
    status: 'ready',
    disabledReason: 'BPZ save is not wired yet',
    tooltip: 'Save all projects in the current BPZ workspace',
    phase: 2,
  },
  {
    id: 'bp.file.exportBps',
    capability: 'bp.file.exportBps',
    label: 'Export BPS...',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/vue/modals/export/bps.vue',
    status: 'ready',
    disabledReason: 'BPS export is not wired yet',
    tooltip: 'Export the active box pleat project as BPS',
    phase: 8,
  },
  {
    id: 'bp.file.exportBpz',
    capability: 'bp.file.exportBpz',
    label: 'Export BPZ...',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/vue/modals/export/bpz.vue',
    status: 'ready',
    disabledReason: 'BPZ export is not wired yet',
    tooltip: 'Export the current box pleat workspace as BPZ',
    phase: 8,
  },
  {
    id: 'bp.file.exportCp',
    capability: 'bp.file.exportCp',
    label: 'Export BP CP...',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/vue/modals/export/cp.vue',
    status: 'ready',
    disabledReason: 'BP CP export is not wired yet',
    tooltip: 'Export the selected BP crease pattern as CP',
    phase: 8,
  },
  {
    id: 'bp.file.exportFold',
    capability: 'bp.file.exportFold',
    label: 'Export BP FOLD...',
    group: 'file',
    placement: 'menu',
    upstream: 'src/client/plugins/cp/fold.ts',
    status: 'ready',
    disabledReason: 'BP FOLD export is not wired yet',
    tooltip: 'Export the selected BP crease pattern as FOLD',
    phase: 8,
  },
  {
    id: 'bp.file.exportSvg',
    capability: 'bp.file.exportSvg',
    label: 'Export BP SVG...',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/vue/modals/export/svg.vue',
    status: 'ready',
    disabledReason: 'BP SVG export is not wired yet',
    tooltip: 'Export the BP packing or crease pattern view as SVG',
    phase: 8,
  },
  {
    id: 'bp.file.exportPng',
    capability: 'bp.file.exportPng',
    label: 'Export BP PNG...',
    group: 'file',
    placement: 'menu',
    upstream: 'src/app/vue/modals/export/png.vue',
    status: 'ready',
    disabledReason: 'BP PNG export is not wired yet',
    tooltip: 'Export the BP packing or crease pattern view as PNG',
    phase: 8,
  },
  {
    id: 'bp.view.tree',
    capability: 'bp.view.tree',
    label: 'BP Tree',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/app/vue/panel/design.vue',
    status: 'ready',
    disabledReason: 'BP tree view is not wired yet',
    tooltip: 'Show the BP tree authoring surface',
    phase: 3,
  },
  {
    id: 'bp.view.packing',
    capability: 'bp.view.packing',
    label: 'BP Editor',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/project/components/layout/layout.ts',
    status: 'ready',
    disabledReason: 'BP Editor is not wired yet',
    tooltip: 'Show the BP editor for flaps, rivers, and conflicts',
    phase: 4,
  },
  {
    id: 'bp.view.creasePattern',
    capability: 'bp.view.creasePattern',
    label: 'BP Crease Pattern',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/app/vue/modals/export/cp.vue',
    status: 'ready',
    disabledReason: 'BP crease pattern view is not wired yet',
    tooltip: 'Generate and open the BP crease pattern in the CP pane',
    phase: 8,
  },
  {
    id: 'bp.view.fit',
    capability: 'bp.view.fit',
    label: 'Fit BP View',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/controllers/zoomController.ts',
    status: 'ready',
    disabledReason: 'BP viewport controls are not wired yet',
    tooltip: 'Fit the active BP view to the viewport',
    phase: 4,
  },
  {
    id: 'bp.view.actualSize',
    capability: 'bp.view.actualSize',
    label: 'Actual BP Size',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/controllers/zoomController.ts',
    status: 'ready',
    disabledReason: 'BP viewport controls are not wired yet',
    tooltip: 'Show the active BP view at actual size',
    phase: 4,
  },
  {
    id: 'bp.view.toggleGrid',
    capability: 'bp.view.toggleGrid',
    label: 'Toggle BP Grid',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/shared/layers.ts',
    status: 'ready',
    disabledReason: 'BP layer toggles are not wired yet',
    tooltip: 'Show or hide the BP grid layer',
    phase: 9,
  },
  {
    id: 'bp.view.toggleHinges',
    capability: 'bp.view.toggleHinges',
    label: 'Toggle BP Hinges',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/shared/layers.ts',
    status: 'ready',
    disabledReason: 'BP layer toggles are not wired yet',
    tooltip: 'Show or hide BP hinge contours',
    phase: 9,
  },
  {
    id: 'bp.view.toggleRidges',
    capability: 'bp.view.toggleRidges',
    label: 'Toggle BP Ridges',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/shared/layers.ts',
    status: 'ready',
    disabledReason: 'BP layer toggles are not wired yet',
    tooltip: 'Show or hide BP ridge lines',
    phase: 9,
  },
  {
    id: 'bp.view.toggleAxisParallels',
    capability: 'bp.view.toggleAxisParallels',
    label: 'Toggle Axis Parallels',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/shared/layers.ts',
    status: 'ready',
    disabledReason: 'BP layer toggles are not wired yet',
    tooltip: 'Show or hide device axis-parallel lines',
    phase: 9,
  },
  {
    id: 'bp.view.toggleLabels',
    capability: 'bp.view.toggleLabels',
    label: 'Toggle BP Labels',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/shared/layers.ts',
    status: 'ready',
    disabledReason: 'BP layer toggles are not wired yet',
    tooltip: 'Show or hide BP tree and packing labels',
    phase: 9,
  },
  {
    id: 'bp.view.toggleDots',
    capability: 'bp.view.toggleDots',
    label: 'Toggle BP Dots',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/shared/layers.ts',
    status: 'ready',
    disabledReason: 'BP layer toggles are not wired yet',
    tooltip: 'Show or hide BP flap dots',
    phase: 9,
  },
  {
    id: 'bp.view.toggleInvalidJunctions',
    capability: 'bp.view.toggleInvalidJunctions',
    label: 'Toggle BP Conflicts',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/shared/layers.ts',
    status: 'ready',
    disabledReason: 'BP layer toggles are not wired yet',
    tooltip: 'Show or hide invalid junction overlays',
    phase: 9,
  },
  {
    id: 'bp.view.toggleSelectionShade',
    capability: 'bp.view.toggleSelectionShade',
    label: 'Toggle BP Selection Shade',
    group: 'view',
    placement: 'toolbar',
    upstream: 'src/client/shared/layers.ts',
    status: 'ready',
    disabledReason: 'BP layer toggles are not wired yet',
    tooltip: 'Show or hide BP selection shading',
    phase: 9,
  },
  {
    id: 'bp.tree.addLeaf',
    capability: 'bp.tree.addLeaf',
    label: 'Add BP Leaf',
    group: 'tree',
    placement: 'tree-context',
    upstream: 'src/client/project/components/tree/vertex.ts:addLeaf',
    status: 'ready',
    disabledReason: 'BP tree editing is not wired yet',
    tooltip: 'Add a leaf to the selected BP tree vertex',
    phase: 3,
    selectionRequirement: 'BP vertex',
  },
  {
    id: 'bp.tree.deleteLeaf',
    capability: 'bp.tree.deleteLeaf',
    label: 'Delete BP Leaf',
    group: 'tree',
    placement: 'tree-context',
    upstream: 'src/client/project/components/tree/vertex.ts:delete',
    status: 'ready',
    disabledReason: 'BP tree editing is not wired yet',
    tooltip: 'Delete the selected BP tree leaf',
    phase: 3,
    selectionRequirement: 'BP leaf vertex',
  },
  {
    id: 'bp.tree.joinVertex',
    capability: 'bp.tree.joinVertex',
    label: 'Join BP Vertex',
    group: 'tree',
    placement: 'tree-context',
    upstream: 'src/client/project/components/tree/vertex.ts:join',
    status: 'ready',
    disabledReason: 'BP tree editing is not wired yet',
    tooltip: 'Join a degree-2 BP tree vertex',
    phase: 3,
    selectionRequirement: 'degree-2 BP vertex',
  },
  {
    id: 'bp.tree.splitEdge',
    capability: 'bp.tree.splitEdge',
    label: 'Split BP Edge',
    group: 'tree',
    placement: 'tree-context',
    upstream: 'src/client/project/components/tree/edge.ts:split',
    status: 'ready',
    disabledReason: 'BP tree editing is not wired yet',
    tooltip: 'Split the selected BP tree edge',
    phase: 3,
    selectionRequirement: 'BP tree edge',
  },
  {
    id: 'bp.tree.mergeEdge',
    capability: 'bp.tree.mergeEdge',
    label: 'Merge BP Edge',
    group: 'tree',
    placement: 'tree-context',
    upstream: 'src/client/project/components/tree/edge.ts:merge',
    status: 'ready',
    disabledReason: 'BP tree editing is not wired yet',
    tooltip: 'Merge or delete the selected BP tree edge',
    phase: 3,
    selectionRequirement: 'BP tree edge',
  },
  {
    id: 'bp.tree.updateVertexName',
    capability: 'bp.tree.updateVertexName',
    label: 'Rename BP Vertex',
    group: 'tree',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/vertex.vue',
    status: 'ready',
    disabledReason: 'BP tree inspector editing is not wired yet',
    tooltip: 'Update the selected BP vertex name',
    phase: 3,
    selectionRequirement: 'BP vertex',
  },
  {
    id: 'bp.tree.updateVertexLocation',
    capability: 'bp.tree.updateVertexLocation',
    label: 'Move BP Vertex',
    group: 'tree',
    placement: 'hidden-ui-only',
    upstream: 'src/client/project/components/tree/vertex.ts:onMove',
    status: 'ready',
    disabledReason: 'BP tree dragging is not wired yet',
    tooltip: 'Move a BP tree vertex through drag or inspector input',
    phase: 3,
    selectionRequirement: 'BP vertex',
  },
  {
    id: 'bp.tree.updateEdgeLength',
    capability: 'bp.tree.updateEdgeLength',
    label: 'Set BP Edge Length',
    group: 'tree',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/edge.vue',
    status: 'ready',
    disabledReason: 'BP tree inspector editing is not wired yet',
    tooltip: 'Set the selected BP tree edge length',
    phase: 3,
    selectionRequirement: 'BP tree edge',
  },
  {
    id: 'bp.tree.goToDual',
    capability: 'bp.tree.goToDual',
    label: 'Go To BP Dual',
    group: 'tree',
    placement: 'tree-context',
    upstream: 'src/client/project/components/tree/*:goToDual',
    status: 'ready',
    disabledReason: 'BP linked selection is not wired yet',
    tooltip: 'Select the matching flap or river in the BP Editor',
    phase: 3,
    selectionRequirement: 'BP vertex or edge',
  },
  {
    id: 'bp.layout.goToDual',
    capability: 'bp.layout.goToDual',
    label: 'Go To BP Source',
    group: 'layout',
    placement: 'packing-context',
    upstream: 'src/client/project/components/layout/*:goToDual',
    status: 'ready',
    disabledReason: 'BP linked selection is not wired yet',
    tooltip: 'Select the matching tree vertex or edge',
    phase: 4,
    selectionRequirement: 'BP flap, river, stretch, or device',
  },
  {
    id: 'bp.layout.moveFlap',
    capability: 'bp.layout.moveFlap',
    label: 'Move BP Flap',
    group: 'layout',
    placement: 'hidden-ui-only',
    upstream: 'src/client/project/components/layout/flap.ts:onMove',
    status: 'ready',
    disabledReason: 'BP flap dragging is not wired yet',
    tooltip: 'Move selected BP flaps with grid constraints',
    phase: 5,
    selectionRequirement: 'BP flap',
  },
  {
    id: 'bp.layout.resizeFlap',
    capability: 'bp.layout.resizeFlap',
    label: 'Resize BP Flap',
    group: 'layout',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/flap.vue',
    status: 'ready',
    disabledReason: 'BP flap size editing is not wired yet',
    tooltip: 'Update selected BP flap width and height',
    phase: 5,
    selectionRequirement: 'BP flap',
  },
  {
    id: 'bp.layout.updateFlapRadius',
    capability: 'bp.layout.updateFlapRadius',
    label: 'Set BP Flap Radius',
    group: 'layout',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/flap.vue',
    status: 'planned',
    disabledReason: 'BP flap radius editing is not wired yet',
    tooltip: 'Update the selected BP flap radius and source edge length',
    phase: 5,
    selectionRequirement: 'BP flap',
  },
  // One command, not two: upstream's river panel has a single number field,
  // labelled Width and bound to the dual edge's length (`River.length` is a
  // proxy for `Edge.length`). `bp.layout.updateRiverLength` used to sit here as
  // its twin and named the same edit.
  {
    id: 'bp.layout.updateRiverWidth',
    capability: 'bp.layout.updateRiverWidth',
    label: 'Set BP River Width',
    group: 'layout',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/river.vue',
    status: 'ready',
    disabledReason: 'Select a BP river first',
    tooltip: 'Update selected BP river width',
    phase: 5,
    selectionRequirement: 'BP river',
  },
  {
    id: 'bp.layout.deleteFlap',
    capability: 'bp.layout.deleteFlap',
    label: 'Delete BP Flap',
    group: 'layout',
    placement: 'packing-context',
    upstream: 'src/client/project/components/layout/flap.ts:delete',
    status: 'planned',
    disabledReason: 'BP flap deletion is not wired yet',
    tooltip: 'Delete the selected BP flap',
    phase: 5,
    selectionRequirement: 'BP flap',
  },
  {
    id: 'bp.layout.deleteRiver',
    capability: 'bp.layout.deleteRiver',
    label: 'Delete BP River',
    group: 'layout',
    placement: 'packing-context',
    upstream: 'src/client/project/components/layout/river.ts:delete',
    status: 'ready',
    disabledReason: 'Select a BP river first',
    tooltip: 'Delete or merge the selected BP river',
    phase: 5,
    selectionRequirement: 'BP river',
  },
  // Doubling and halving the whole design, in the Design menu. Distinct from the
  // sheet toolbar's +/- buttons, which step the grid size by one unit and rescale
  // nothing (see `bp.layout.growSheet` / `bp.layout.shrinkSheet`).
  {
    id: 'bp.layout.subdivide',
    capability: 'bp.layout.subdivide',
    label: 'Subdivide BP Sheet',
    group: 'layout',
    placement: 'menu',
    upstream: 'src/client/project/components/sheet.ts:subdivide',
    status: 'ready',
    disabledReason: 'Switch to the BP Editor before subdividing the sheet',
    tooltip: 'Subdivide the BP sheet',
    phase: 5,
  },
  {
    id: 'bp.layout.unsubdivide',
    capability: 'bp.layout.unsubdivide',
    label: 'Un-subdivide BP Sheet',
    group: 'layout',
    placement: 'menu',
    upstream: 'src/client/project/components/sheet.ts:subdivide',
    status: 'ready',
    disabledReason: 'Switch to the BP Editor before un-subdividing the sheet',
    tooltip: 'Halve the BP sheet grid (disabled unless flaps sit on even lines)',
    phase: 5,
  },
  {
    id: 'bp.layout.growSheet',
    capability: 'bp.layout.growSheet',
    label: 'Increase BP Sheet Grid Size',
    group: 'layout',
    placement: 'toolbar',
    upstream: 'src/app/vue/panel/grid/*.vue',
    status: 'ready',
    disabledReason: 'Switch to the BP Editor before resizing the sheet',
    tooltip: 'Add one grid unit to each BP sheet dimension',
    phase: 5,
  },
  {
    id: 'bp.layout.shrinkSheet',
    capability: 'bp.layout.shrinkSheet',
    label: 'Decrease BP Sheet Grid Size',
    group: 'layout',
    placement: 'toolbar',
    upstream: 'src/app/vue/panel/grid/*.vue',
    status: 'ready',
    disabledReason: 'Switch to the BP Editor before resizing the sheet',
    tooltip: 'Remove one grid unit from each BP sheet dimension (disabled unless the flaps fit)',
    phase: 5,
  },
  {
    id: 'bp.layout.rotateRight',
    capability: 'bp.layout.rotateRight',
    label: 'Rotate BP Sheet Right',
    group: 'layout',
    placement: 'menu',
    upstream: 'src/client/project/components/sheet.ts:rotate',
    status: 'ready',
    disabledReason: 'Switch to the BP Editor before rotating the sheet',
    tooltip: 'Rotate the BP sheet clockwise',
    phase: 5,
  },
  {
    id: 'bp.layout.rotateLeft',
    capability: 'bp.layout.rotateLeft',
    label: 'Rotate BP Sheet Left',
    group: 'layout',
    placement: 'menu',
    upstream: 'src/client/project/components/sheet.ts:rotate',
    status: 'ready',
    disabledReason: 'Switch to the BP Editor before rotating the sheet',
    tooltip: 'Rotate the BP sheet counterclockwise',
    phase: 5,
  },
  {
    id: 'bp.layout.flipHorizontal',
    capability: 'bp.layout.flipHorizontal',
    label: 'Flip BP Sheet Horizontal',
    group: 'layout',
    placement: 'menu',
    upstream: 'src/client/project/components/sheet.ts:flip',
    status: 'ready',
    disabledReason: 'Switch to the BP Editor before flipping the sheet',
    tooltip: 'Flip the BP sheet horizontally',
    phase: 5,
  },
  {
    id: 'bp.layout.flipVertical',
    capability: 'bp.layout.flipVertical',
    label: 'Flip BP Sheet Vertical',
    group: 'layout',
    placement: 'menu',
    upstream: 'src/client/project/components/sheet.ts:flip',
    status: 'ready',
    disabledReason: 'Switch to the BP Editor before flipping the sheet',
    tooltip: 'Flip the BP sheet vertically',
    phase: 5,
  },
  {
    id: 'bp.layout.updateSheet',
    capability: 'bp.layout.updateSheet',
    label: 'Update BP Sheet',
    group: 'layout',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/grid/*.vue',
    status: 'ready',
    disabledReason: 'Switch to the BP Editor before editing the sheet',
    tooltip: 'Update BP sheet size and grid settings',
    phase: 5,
  },
  {
    id: 'bp.layout.changeGridType',
    capability: 'bp.layout.changeGridType',
    label: 'Change BP Grid Type',
    group: 'layout',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/grid/*.vue',
    status: 'ready',
    disabledReason: 'Switch to the BP Editor before changing the grid type',
    tooltip: 'Switch between rectangular and diagonal BP grids',
    phase: 5,
  },
  {
    id: 'bp.layout.nudgeSelection',
    capability: 'bp.layout.nudgeSelection',
    label: 'Nudge BP Selection',
    group: 'layout',
    placement: 'hidden-ui-only',
    upstream: 'src/app/vue/gadgets/dpad.vue',
    status: 'ready',
    disabledReason: 'Select a BP flap or device first',
    tooltip: 'Nudge selected BP flaps or a BP device by keyboard or d-pad',
    phase: 5,
    selectionRequirement: 'BP flap or device',
  },
  {
    id: 'bp.layout.completeStretch',
    capability: 'bp.layout.completeStretch',
    label: 'Complete BP Stretch',
    group: 'stretch',
    placement: 'inspector',
    upstream: 'src/client/project/components/layout/stretch.ts:complete',
    status: 'ready',
    disabledReason: 'Select a BP stretch first',
    tooltip: 'Complete the selected stretch repository',
    phase: 6,
    selectionRequirement: 'BP stretch',
  },
  {
    id: 'bp.layout.nextConfig',
    capability: 'bp.layout.nextConfig',
    label: 'Next BP Config',
    group: 'stretch',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/stretch.vue',
    status: 'ready',
    disabledReason: 'Select a BP stretch with multiple configurations',
    tooltip: 'Select the next stretch configuration',
    phase: 6,
    selectionRequirement: 'BP stretch',
    shortcut: ']',
  },
  {
    id: 'bp.layout.prevConfig',
    capability: 'bp.layout.prevConfig',
    label: 'Previous BP Config',
    group: 'stretch',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/stretch.vue',
    status: 'ready',
    disabledReason: 'Select a BP stretch with multiple configurations',
    tooltip: 'Select the previous stretch configuration',
    phase: 6,
    selectionRequirement: 'BP stretch',
    shortcut: '[',
  },
  {
    id: 'bp.layout.nextPattern',
    capability: 'bp.layout.nextPattern',
    label: 'Next BP Pattern',
    group: 'stretch',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/stretch.vue',
    status: 'ready',
    disabledReason: 'Select a BP stretch with multiple patterns',
    tooltip: 'Select the next pattern for the current stretch configuration',
    phase: 6,
    selectionRequirement: 'BP stretch',
    shortcut: 'Shift+]',
  },
  {
    id: 'bp.layout.prevPattern',
    capability: 'bp.layout.prevPattern',
    label: 'Previous BP Pattern',
    group: 'stretch',
    placement: 'inspector',
    upstream: 'src/app/vue/panel/stretch.vue',
    status: 'ready',
    disabledReason: 'Select a BP stretch with multiple patterns',
    tooltip: 'Select the previous pattern for the current stretch configuration',
    phase: 6,
    selectionRequirement: 'BP stretch',
    shortcut: 'Shift+[',
  },
  {
    id: 'bp.layout.moveDevice',
    capability: 'bp.layout.moveDevice',
    label: 'Move BP Device',
    group: 'stretch',
    placement: 'hidden-ui-only',
    upstream: 'src/client/project/components/layout/device.ts:onMove',
    status: 'ready',
    disabledReason: 'Select a BP device first',
    tooltip: 'Move the selected BP device along its constrained range',
    phase: 6,
    selectionRequirement: 'BP device',
  },
  {
    id: 'bp.optimize.layout',
    capability: 'bp.optimize.layout',
    label: 'Optimize BP Layout',
    group: 'optimizer',
    placement: 'toolbar',
    upstream: 'src/app/vue/modals/optimizer.vue',
    status: 'ready',
    disabledReason: 'Add BP tree edges before optimizing',
    tooltip: 'Run the BP layout optimizer',
    phase: 7,
  },
  {
    id: 'bp.optimize.cancel',
    capability: 'bp.optimize.cancel',
    label: 'Cancel BP Optimization',
    group: 'optimizer',
    placement: 'toolbar',
    upstream: 'src/app/vue/modals/optimizer.vue',
    status: 'ready',
    disabledReason: 'No BP optimizer is running',
    tooltip: 'Stop the running BP optimizer',
    phase: 7,
  },
  {
    id: 'bp.optimize.skip',
    capability: 'bp.optimize.skip',
    label: 'Skip BP Optimizer Stage',
    group: 'optimizer',
    placement: 'toolbar',
    upstream: 'src/app/vue/modals/optimizer.vue',
    status: 'planned',
    disabledReason: 'BP optimizer skip is not wired yet',
    tooltip: 'Skip the current optimizer stage when the backend permits it',
    phase: 7,
  },
  {
    id: 'bp.optimize.applyResult',
    capability: 'bp.optimize.applyResult',
    label: 'Apply BP Optimizer Result',
    group: 'optimizer',
    placement: 'toolbar',
    upstream: 'src/app/vue/modals/optimizer.vue',
    status: 'planned',
    disabledReason: 'BP optimizer result application is not wired yet',
    tooltip: 'Apply the current optimizer result to the active project',
    phase: 7,
  },
  {
    id: 'bp.optimize.openResultAsNew',
    capability: 'bp.optimize.openResultAsNew',
    label: 'Open BP Result As New',
    group: 'optimizer',
    placement: 'toolbar',
    upstream: 'src/app/vue/modals/optimizer.vue',
    status: 'planned',
    disabledReason: 'BP optimizer open-new behavior is not wired yet',
    tooltip: 'Open the optimizer result as a new BP project',
    phase: 7,
  },
  {
    id: 'bp.diagnostics.selectConflict',
    capability: 'bp.diagnostics.selectConflict',
    label: 'Select BP Conflict',
    group: 'diagnostics',
    placement: 'diagnostics',
    upstream: 'src/client/project/components/layout/junction.ts',
    status: 'planned',
    disabledReason: 'BP conflict diagnostics are not wired yet',
    tooltip: 'Select a BP invalid junction and its related objects',
    phase: 4,
    selectionRequirement: 'BP invalid junction',
  },
  {
    id: 'bp.diagnostics.clearSelection',
    capability: 'bp.diagnostics.clearSelection',
    label: 'Clear BP Diagnostic Selection',
    group: 'diagnostics',
    placement: 'diagnostics',
    upstream: 'src/client/controllers/selectionController.ts',
    status: 'planned',
    disabledReason: 'BP diagnostics are not wired yet',
    tooltip: 'Clear selected BP diagnostic overlays',
    phase: 4,
  },
  {
    id: 'bp.workspace.cloneProject',
    capability: 'bp.workspace.cloneProject',
    label: 'Clone BP Project',
    group: 'workspace',
    placement: 'menu',
    upstream: 'src/app/services/workspaceService.ts:clone',
    status: 'ready',
    disabledReason: 'BP workspace tabs are not wired yet',
    tooltip: 'Clone the active BP project',
    phase: 10,
  },
  {
    id: 'bp.workspace.closeProject',
    capability: 'bp.workspace.closeProject',
    label: 'Close BP Project',
    group: 'workspace',
    placement: 'menu',
    upstream: 'src/app/services/workspaceService.ts:close',
    status: 'ready',
    disabledReason: 'BP workspace tabs are not wired yet',
    tooltip: 'Close the active BP project',
    phase: 10,
  },
  {
    id: 'bp.workspace.closeOthers',
    capability: 'bp.workspace.closeOthers',
    label: 'Close Other BP Projects',
    group: 'workspace',
    placement: 'menu',
    upstream: 'src/app/services/workspaceService.ts:closeOthers',
    status: 'ready',
    disabledReason: 'BP workspace tabs are not wired yet',
    tooltip: 'Close all BP projects except the active one',
    phase: 10,
  },
  {
    id: 'bp.workspace.closeRight',
    capability: 'bp.workspace.closeRight',
    label: 'Close BP Projects To The Right',
    group: 'workspace',
    placement: 'menu',
    upstream: 'src/app/services/workspaceService.ts:closeRight',
    status: 'ready',
    disabledReason: 'BP workspace tabs are not wired yet',
    tooltip: 'Close BP project tabs to the right of the active tab',
    phase: 10,
  },
  {
    id: 'bp.workspace.closeAll',
    capability: 'bp.workspace.closeAll',
    label: 'Close All BP Projects',
    group: 'workspace',
    placement: 'menu',
    upstream: 'src/app/services/workspaceService.ts:closeAll',
    status: 'ready',
    disabledReason: 'BP workspace tabs are not wired yet',
    tooltip: 'Close all BP projects in the workspace',
    phase: 10,
  },
  {
    id: 'bp.workspace.saveAll',
    capability: 'bp.workspace.saveAll',
    label: 'Save All BP Projects',
    group: 'workspace',
    placement: 'menu',
    upstream: 'src/app/services/workspaceService.ts:saveAll',
    status: 'ready',
    disabledReason: 'BP workspace save-all is not wired yet',
    tooltip: 'Save all BP projects in the workspace',
    phase: 10,
  },
] as const satisfies readonly OristudioBpCommandDefinition[];

export type OristudioBpCommandId = (typeof ORISTUDIO_BP_COMMANDS)[number]['id'];
export type OristudioBpCapabilityId = (typeof ORISTUDIO_BP_COMMANDS)[number]['capability'];

export const ORISTUDIO_BP_COMMAND_IDS = ORISTUDIO_BP_COMMANDS.map(
  (command) => command.id
) as readonly OristudioBpCommandId[];

export const ORISTUDIO_BP_CAPABILITY_IDS = ORISTUDIO_BP_COMMANDS.map(
  (command) => command.capability
) as readonly OristudioBpCapabilityId[];

export function isOristudioBpCommandId(id: string): id is OristudioBpCommandId {
  return (ORISTUDIO_BP_COMMAND_IDS as readonly string[]).includes(id);
}

export function isOristudioBpCapabilityId(id: string): id is OristudioBpCapabilityId {
  return (ORISTUDIO_BP_CAPABILITY_IDS as readonly string[]).includes(id);
}
